// ─── Core Step Interface ────────────────────────────────────────────────────

export interface Step {
  id: number;
  action: string;
  description: string;
  codeLine: number;
  payload: any;
}


// ─── Sorting ────────────────────────────────────────────────────────────────

export interface SortingPayload {
  array: number[];
  comparing?: number[];
  swapping?: number[];
  sorted?: number[];
  pivot?: number;
  left?: number;
  right?: number;
  mid?: number;
}

// ─── Graph ──────────────────────────────────────────────────────────────────

export interface GraphNode {
  id: string;
  label?: string;
  x?: number;
  y?: number;
}

export interface GraphEdge {
  source: string;
  target: string;
  weight?: number;
}

export interface GraphData {
  nodes: GraphNode[];
  edges: GraphEdge[];
  directed?: boolean;
  weighted?: boolean;
}

export interface GraphPayload {
  graph: GraphData;
  visited: string[];
  queue?: string[];
  stack?: string[];
  current?: string;
  distances?: Record<string, number>;
  previous?: Record<string, string | null>;
  path?: string[];
  mstEdges?: GraphEdge[];
}

// ─── Tree ───────────────────────────────────────────────────────────────────

export interface TreeNode {
  id: string;
  value: number;
  left?: TreeNode | null;
  right?: TreeNode | null;
  height?: number;
  parent?: string | null;
  balance?: number;
  color?: 'RED' | 'BLACK';
  isAST?: boolean;
  operator?: string;
}

export interface TreePayload {
  root: TreeNode | null;
  current?: string | null;
  visited?: string[];
  callStack?: string[];
  result?: number[];
  comparing?: string | null;
  rotationType?: string;
}

// ─── Dynamic Programming ────────────────────────────────────────────────────

export interface DPPayload {
  table: number[][];
  rows?: string[];
  cols?: string[];
  activeCell?: [number, number];
  dependsOn?: Array<[number, number]>;
  result?: number;
  memo?: Record<string, number>;
}

// ─── Backtracking (N-Queens) ────────────────────────────────────────────────

export interface BacktrackingPayload {
  grid: number[][]; // 0 for empty, 1 for queen, 2 for conflict/checked
  row?: number;
  col?: number;
  solutionsCount?: number;
  currentQueens?: Array<[number, number]>;
}

// ─── Recursion ──────────────────────────────────────────────────────────────

export interface StackFrame {
  id: string;
  funcName: string;
  args: Record<string, unknown>;
  returnValue?: unknown;
  isReturning?: boolean;
}

export interface RecursionPayload {
  callStack: StackFrame[];
  currentFrameId?: string;
  result?: unknown;
  disks?: Array<{ disk: number; peg: string }>;
  pegs?: { A: number[]; B: number[]; C: number[] };
}

// ─── Data Structures ────────────────────────────────────────────────────────
export interface DataStructurePayload {
  type: 'stack' | 'queue' | 'linked-list';
  elements: number[];
  nodes?: Array<{ id: string; value: number; nextId: string | null; prevId?: string | null }>;
  headId?: string | null;
  topIndex?: number;
  frontIndex?: number;
  rearIndex?: number;
  activeIndex?: number;
  activeNodeId?: string | null;
  actionNodeId?: string | null;
  actionType?: 'push' | 'pop' | 'peek' | 'enqueue' | 'dequeue' | 'traverse' | 'insert' | 'delete';
}

// ─── Algorithm Metadata ─────────────────────────────────────────────────────

// ─── Algorithm Metadata ─────────────────────────────────────────────────────

export type AlgorithmCategory =
  | 'searching'
  | 'sorting'
  | 'recursion'
  | 'backtracking'
  | 'stack'
  | 'queue-deque'
  | 'linkedlist'
  | 'binarytrees'
  | 'bst'
  | 'balancedtrees'
  | 'heap'
  | 'trie'
  | 'hashing'
  | 'graphtraversal'
  | 'shortestpath'
  | 'mst'
  | 'topological'
  | 'connectivity'
  | 'cycledetection'
  | 'dp'
  | 'greedy'
  | 'divideandconquer'
  | 'strings'
  | 'bitmanipulation'
  | 'numbertheory'
  | 'matrix'
  | 'geometry'
  | 'networkflow'
  | 'segmenttrees'
  | 'advancedgraph'
  | 'randomized'
  | 'parallel'
  | 'ml';

export interface AlgorithmMeta {
  id: string;
  name: string;
  category: AlgorithmCategory;
  timeComplexity: string;
  spaceComplexity: string;
  description: string;
  tags: string[];
  mode?: 'interactive' | 'concept'; // 'interactive' is default if omitted
}

export const ALGORITHM_REGISTRY: AlgorithmMeta[] = [
  // 1. Searching Algorithms
  {
    id: 'linear-search',
    name: 'Linear Search',
    category: 'searching',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Sequentially checks each element of the list until a match is found.',
    tags: ['array', 'search', 'sequential'],
    mode: 'interactive',
  },
  {
    id: 'binary-search',
    name: 'Binary Search',
    category: 'searching',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    description: 'Finds the position of a target value within a sorted array by dividing search interval in half.',
    tags: ['array', 'search', 'divide-and-conquer', 'sorted'],
    mode: 'interactive',
  },
  {
    id: 'ternary-search',
    name: 'Ternary Search',
    category: 'searching',
    timeComplexity: 'O(log₃ n)',
    spaceComplexity: 'O(1)',
    description: 'Finds the position of a target value within a sorted array by dividing the search space into three parts.',
    tags: ['array', 'search', 'divide-and-conquer', 'sorted'],
    mode: 'interactive',
  },
  {
    id: 'jump-search',
    name: 'Jump Search',
    category: 'searching',
    timeComplexity: 'O(√n)',
    spaceComplexity: 'O(1)',
    description: 'Searches in a sorted array by jumping ahead by fixed steps (usually √n) and then performing a linear search.',
    tags: ['array', 'search', 'block-search', 'sorted'],
    mode: 'concept',
  },
  {
    id: 'exponential-search',
    name: 'Exponential Search',
    category: 'searching',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    description: 'Finds a range where the target resides by doubling indices exponentially, then applies binary search in that range.',
    tags: ['array', 'search', 'exponential', 'sorted'],
    mode: 'concept',
  },
  {
    id: 'interpolation-search',
    name: 'Interpolation Search',
    category: 'searching',
    timeComplexity: 'O(log log n) avg',
    spaceComplexity: 'O(1)',
    description: 'An improved binary search variant for uniformly distributed sorted arrays, estimating target location like searching a phonebook.',
    tags: ['array', 'search', 'sorted', 'uniform-distribution'],
    mode: 'concept',
  },
  {
    id: 'fibonacci-search',
    name: 'Fibonacci Search',
    category: 'searching',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    description: 'A comparison-based search algorithm that uses Fibonacci numbers to divide the search intervals in a sorted array.',
    tags: ['array', 'search', 'fibonacci', 'sorted'],
    mode: 'concept',
  },

  // 2. Sorting Algorithms
  {
    id: 'bubble-sort',
    name: 'Bubble Sort',
    category: 'sorting',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(1)',
    description: 'Repeatedly swaps adjacent elements that are in the wrong order.',
    tags: ['simple', 'in-place', 'stable'],
    mode: 'interactive',
  },
  {
    id: 'selection-sort',
    name: 'Selection Sort',
    category: 'sorting',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(1)',
    description: 'Repeatedly finds the minimum element from the unsorted part and puts it at the beginning.',
    tags: ['simple', 'in-place', 'unstable'],
    mode: 'interactive',
  },
  {
    id: 'insertion-sort',
    name: 'Insertion Sort',
    category: 'sorting',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(1)',
    description: 'Builds the sorted array one element at a time by insertion.',
    tags: ['simple', 'in-place', 'stable', 'adaptive'],
    mode: 'interactive',
  },
  {
    id: 'merge-sort',
    name: 'Merge Sort',
    category: 'sorting',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    description: 'Divides array in half, sorts each half, then merges them.',
    tags: ['divide-and-conquer', 'stable', 'recursive'],
    mode: 'interactive',
  },
  {
    id: 'quick-sort',
    name: 'Quick Sort',
    category: 'sorting',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(log n)',
    description: 'Partitions array around a pivot element recursively.',
    tags: ['divide-and-conquer', 'in-place', 'recursive'],
    mode: 'interactive',
  },
  {
    id: 'heap-sort',
    name: 'Heap Sort',
    category: 'sorting',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(1)',
    description: 'Builds a max-heap then extracts elements one by one.',
    tags: ['in-place', 'heap', 'selection'],
    mode: 'interactive',
  },
  {
    id: 'counting-sort',
    name: 'Counting Sort',
    category: 'sorting',
    timeComplexity: 'O(n + k)',
    spaceComplexity: 'O(k)',
    description: 'Non-comparison based sorting using counts of keys in a specific range.',
    tags: ['non-comparison', 'stable', 'integer-sorting'],
    mode: 'concept',
  },
  {
    id: 'radix-sort',
    name: 'Radix Sort',
    category: 'sorting',
    timeComplexity: 'O(d × (n + k))',
    spaceComplexity: 'O(n + k)',
    description: 'Sorts integers digit by digit, from least significant to most significant, using Counting Sort as a subroutine.',
    tags: ['non-comparison', 'stable', 'integer-sorting', 'digit-by-digit'],
    mode: 'concept',
  },
  {
    id: 'bucket-sort',
    name: 'Bucket Sort',
    category: 'sorting',
    timeComplexity: 'O(n + k) avg',
    spaceComplexity: 'O(n + k)',
    description: 'Distributes elements into buckets, sorts each bucket individually, and gathers them back.',
    tags: ['non-comparison', 'distribution', 'stable'],
    mode: 'concept',
  },
  {
    id: 'shell-sort',
    name: 'Shell Sort',
    category: 'sorting',
    timeComplexity: 'O(n log² n)',
    spaceComplexity: 'O(1)',
    description: 'An extension of Insertion Sort that allows swapping of far apart elements, narrowing gaps progressively.',
    tags: ['comparison', 'in-place', 'unstable', 'diminishing-increment'],
    mode: 'concept',
  },
  {
    id: 'tim-sort',
    name: 'Tim Sort',
    category: 'sorting',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    description: 'Hybrid sorting algorithm derived from Merge Sort and Insertion Sort. Used as standard in Python and Java.',
    tags: ['hybrid', 'stable', 'adaptive', 'runs'],
    mode: 'concept',
  },
  {
    id: 'introsort',
    name: 'IntroSort',
    category: 'sorting',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(log n)',
    description: 'Hybrid sort starting with Quick Sort, switching to Heap Sort if recursion depth is too high, and Insertion Sort for small arrays.',
    tags: ['hybrid', 'unstable', 'comparison', 'introspective'],
    mode: 'concept',
  },
  {
    id: 'cycle-sort',
    name: 'Cycle Sort',
    category: 'sorting',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(1)',
    description: 'In-place sorting algorithm that minimizes the number of memory writes, theoretically optimal for memory write cost.',
    tags: ['in-place', 'unstable', 'write-optimal'],
    mode: 'concept',
  },
  {
    id: 'comb-sort',
    name: 'Comb Sort',
    category: 'sorting',
    timeComplexity: 'O(n log n) avg',
    spaceComplexity: 'O(1)',
    description: 'Improves Bubble Sort by using a gap size larger than 1 to eliminate turtles (small values near the end of list).',
    tags: ['comparison', 'in-place', 'unstable'],
    mode: 'concept',
  },
  {
    id: 'pigeonhole-sort',
    name: 'Pigeonhole Sort',
    category: 'sorting',
    timeComplexity: 'O(n + N)',
    spaceComplexity: 'O(N)',
    description: 'Suitable for sorting lists of elements where the number of elements (n) and length of range (N) are roughly the same.',
    tags: ['non-comparison', 'integer-sorting', 'stable'],
    mode: 'concept',
  },

  // 3. Recursion
  {
    id: 'factorial',
    name: 'Factorial (Recursion)',
    category: 'recursion',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Demonstrates recursive call stack with factorial computation.',
    tags: ['recursion', 'call-stack', 'classic'],
    mode: 'interactive',
  },
  {
    id: 'tower-of-hanoi',
    name: 'Tower of Hanoi',
    category: 'recursion',
    timeComplexity: 'O(2ⁿ)',
    spaceComplexity: 'O(n)',
    description: 'Move disks between pegs using recursive decomposition.',
    tags: ['recursion', 'classic', 'divide-and-conquer'],
    mode: 'interactive',
  },
  {
    id: 'fibonacci-recursive',
    name: 'Fibonacci (Recursive)',
    category: 'recursion',
    timeComplexity: 'O(2ⁿ)',
    spaceComplexity: 'O(n)',
    description: 'Calculates Fibonacci numbers recursively without memoization, demonstrating exponential call tree growth.',
    tags: ['recursion', 'fibonacci', 'exponential'],
    mode: 'concept',
  },
  {
    id: 'sum-of-n-recursive',
    name: 'Sum of N Numbers',
    category: 'recursion',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Computes sum of first N natural numbers recursively to illustrate base case and head/tail recursion.',
    tags: ['recursion', 'basic'],
    mode: 'concept',
  },
  {
    id: 'power-function-recursive',
    name: 'Power Function (xⁿ)',
    category: 'recursion',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(log n)',
    description: 'Computes power of a number recursively using fast modular exponentiation (divide-and-conquer multiplication).',
    tags: ['recursion', 'divide-and-conquer', 'math'],
    mode: 'concept',
  },
  {
    id: 'binary-search-recursive',
    name: 'Recursive Binary Search',
    category: 'recursion',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(log n)',
    description: 'Performs binary search in a sorted array using recursive boundary partitioning instead of iteration.',
    tags: ['recursion', 'search', 'sorted'],
    mode: 'concept',
  },
  {
    id: 'tree-traversals-recursive',
    name: 'Recursive Tree Traversals',
    category: 'recursion',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    description: 'Traverses binary tree recursively in Inorder, Preorder, and Postorder styles using system stack frames.',
    tags: ['recursion', 'tree', 'traversal'],
    mode: 'concept',
  },

  // 4. Backtracking
  {
    id: 'n-queens',
    name: 'N-Queens (Backtracking)',
    category: 'backtracking',
    timeComplexity: 'O(n!)',
    spaceComplexity: 'O(n)',
    description: 'Place N non-attacking queens on an N×N chessboard.',
    tags: ['backtracking', 'recursion', 'chessboard'],
    mode: 'interactive',
  },
  {
    id: 'sudoku-solver',
    name: 'Sudoku Solver',
    category: 'backtracking',
    timeComplexity: 'O(9^(n²))',
    spaceComplexity: 'O(n²)',
    description: 'Solves a standard 9x9 Sudoku grid by recursively trying digits and backtracking on conflicts.',
    tags: ['backtracking', 'recursion', 'grid'],
    mode: 'concept',
  },
  {
    id: 'rat-in-a-maze',
    name: 'Rat in a Maze',
    category: 'backtracking',
    timeComplexity: 'O(2^(n²))',
    spaceComplexity: 'O(n²)',
    description: 'Finds a path for a rat from source to destination in a maze grid containing obstacles.',
    tags: ['backtracking', 'recursion', 'maze', 'grid'],
    mode: 'concept',
  },
  {
    id: 'word-search',
    name: 'Word Search (Grid)',
    category: 'backtracking',
    timeComplexity: 'O(m × n × 4^L)',
    spaceComplexity: 'O(L)',
    description: 'Finds if a word exists in a 2D character board by traversing adjacent cells recursively.',
    tags: ['backtracking', 'depth-first-search', 'grid', 'strings'],
    mode: 'concept',
  },
  {
    id: 'knights-tour',
    name: "Knight's Tour",
    category: 'backtracking',
    timeComplexity: 'O(8^(N²))',
    spaceComplexity: 'O(N²)',
    description: 'Attempts to move a knight across every single chessboard square exactly once.',
    tags: ['backtracking', 'chessboard', 'puzzle'],
    mode: 'concept',
  },
  {
    id: 'hamiltonian-path',
    name: 'Hamiltonian Path',
    category: 'backtracking',
    timeComplexity: 'O(n!)',
    spaceComplexity: 'O(n)',
    description: 'Determines if there is a path in a graph that visits every vertex exactly once.',
    tags: ['backtracking', 'graph', 'np-complete'],
    mode: 'concept',
  },
  {
    id: 'combination-sum',
    name: 'Combination Sum',
    category: 'backtracking',
    timeComplexity: 'O(2^t)',
    spaceComplexity: 'O(t)',
    description: 'Finds all unique combinations of candidates that sum up to a target number.',
    tags: ['backtracking', 'recursion', 'combinations'],
    mode: 'concept',
  },
  {
    id: 'subset-generation',
    name: 'Subset Generation',
    category: 'backtracking',
    timeComplexity: 'O(2ⁿ)',
    spaceComplexity: 'O(n)',
    description: 'Generates all subsets (power set) of a given array of elements.',
    tags: ['backtracking', 'recursion', 'sets'],
    mode: 'concept',
  },
  {
    id: 'permutations-backtracking',
    name: 'Permutations',
    category: 'backtracking',
    timeComplexity: 'O(n × n!)',
    spaceComplexity: 'O(n)',
    description: 'Generates all possible orderings (permutations) of a set of distinct elements.',
    tags: ['backtracking', 'recursion', 'permutations'],
    mode: 'concept',
  },
  {
    id: 'generate-parentheses',
    name: 'Generate Parentheses',
    category: 'backtracking',
    timeComplexity: 'O(4ⁿ / (n √n))',
    spaceComplexity: 'O(n)',
    description: 'Generates all combinations of well-formed parentheses containing n open and closed brackets.',
    tags: ['backtracking', 'recursion', 'catalan'],
    mode: 'concept',
  },

  // 5. Stack Algorithms
  {
    id: 'stack-ops',
    name: 'Stack Operations',
    category: 'stack',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(n)',
    description: 'Push, Pop, and Peek operations on a Last-In-First-Out (LIFO) stack.',
    tags: ['array', 'stack', 'lifo', 'push', 'pop'],
    mode: 'interactive',
  },
  {
    id: 'postfix-eval',
    name: 'Postfix Evaluation',
    category: 'stack',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Evaluation of mathematical expressions in Postfix (Reverse Polish) notation using a Stack.',
    tags: ['stack', 'expression', 'postfix', 'polish'],
    mode: 'interactive',
  },
  {
    id: 'prefix-eval',
    name: 'Prefix Evaluation',
    category: 'stack',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Evaluation of mathematical expressions in Prefix notation using a Stack.',
    tags: ['stack', 'expression', 'prefix', 'polish'],
    mode: 'interactive',
  },
  {
    id: 'balanced-parentheses',
    name: 'Balanced Parentheses',
    category: 'stack',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Validates bracket nesting in an expression using an open-bracket stack push/pop mapping.',
    tags: ['stack', 'brackets', 'validation'],
    mode: 'concept',
  },
  {
    id: 'next-greater-element',
    name: 'Next Greater Element',
    category: 'stack',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Finds the nearest greater element to the right for each array item in a single pass using a stack.',
    tags: ['stack', 'array', 'monotonic-stack'],
    mode: 'concept',
  },
  {
    id: 'previous-greater-element',
    name: 'Previous Greater Element',
    category: 'stack',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Finds the nearest greater element to the left for each array item using a monotonic stack.',
    tags: ['stack', 'array', 'monotonic-stack'],
    mode: 'concept',
  },
  {
    id: 'stock-span',
    name: 'Stock Span Problem',
    category: 'stack',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Calculates the span of stock prices (consecutive days of lesser/equal price) using a stack.',
    tags: ['stack', 'monotonic-stack', 'finance'],
    mode: 'concept',
  },
  {
    id: 'largest-rectangle-histogram',
    name: 'Largest Rectangle in Histogram',
    category: 'stack',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Finds the maximum rectangular area in a histogram array using a monotonic stack.',
    tags: ['stack', 'monotonic-stack', 'optimization'],
    mode: 'concept',
  },
  {
    id: 'min-stack',
    name: 'Min Stack',
    category: 'stack',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(n)',
    description: 'A stack that supports push, pop, top, and retrieving the minimum element in constant O(1) time.',
    tags: ['stack', 'data-structure-design'],
    mode: 'concept',
  },
  {
    id: 'infix-to-postfix',
    name: 'Infix to Postfix Conversion',
    category: 'stack',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Converts a standard mathematical Infix expression (e.g. A+B) to Postfix (e.g. AB+) using stack operator precedence parsing.',
    tags: ['stack', 'expression', 'compiler'],
    mode: 'concept',
  },
  {
    id: 'prefix-conversion',
    name: 'Infix to Prefix Conversion',
    category: 'stack',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Converts an Infix expression to Prefix notation by reversing strings and parsing operators.',
    tags: ['stack', 'expression', 'compiler'],
    mode: 'concept',
  },
  {
    id: 'monotonic-stack',
    name: 'Monotonic Stack Template',
    category: 'stack',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'A stack skeleton that maintains elements in strict increasing or decreasing order for range queries.',
    tags: ['stack', 'utility'],
    mode: 'concept',
  },

  // 6. Queue & Deque
  {
    id: 'queue-ops',
    name: 'Queue Operations',
    category: 'queue-deque',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(n)',
    description: 'Enqueue and Dequeue operations on a First-In-First-Out (FIFO) queue.',
    tags: ['array', 'queue', 'fifo', 'enqueue', 'dequeue'],
    mode: 'interactive',
  },
  {
    id: 'double-ended-queue',
    name: 'Double-Ended Queue (Deque)',
    category: 'queue-deque',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(n)',
    description: 'A queue where insertion and deletion can occur at both front and rear ends.',
    tags: ['queue', 'deque', 'double-ended'],
    mode: 'interactive',
  },
  {
    id: 'circular-queue',
    name: 'Circular Queue',
    category: 'queue-deque',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(n)',
    description: 'A linear queue that wraps around the end of the array to reuse empty slots.',
    tags: ['queue', 'circular', 'ring-buffer'],
    mode: 'interactive',
  },
  {
    id: 'priority-queue',
    name: 'Priority Queue',
    category: 'queue-deque',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(n)',
    description: 'An abstract data type where elements have priorities, served highest priority first.',
    tags: ['queue', 'heap', 'priority'],
    mode: 'interactive',
  },
  {
    id: 'sliding-window-maximum',
    name: 'Sliding Window Maximum',
    category: 'queue-deque',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(k)',
    description: 'Finds the maximum value in every sliding subarray window of size k using a Deque.',
    tags: ['queue', 'deque', 'sliding-window', 'monotonic'],
    mode: 'concept',
  },
  {
    id: 'first-negative-integer',
    name: 'First Negative in Window',
    category: 'queue-deque',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(k)',
    description: 'Finds the first negative number in every window of size k in an array using a queue.',
    tags: ['queue', 'sliding-window'],
    mode: 'concept',
  },
  {
    id: 'deque-operations',
    name: 'Deque Operations (DLL representation)',
    category: 'queue-deque',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(n)',
    description: 'Visualizes pointer changes when appending/deleting from head/tail of a deque.',
    tags: ['queue', 'deque', 'pointers'],
    mode: 'concept',
  },

  // 7. Linked List
  {
    id: 'singly-linked-list',
    name: 'Singly Linked List',
    category: 'linkedlist',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Nodes connected sequentially, showing search, insertion, and deletion.',
    tags: ['linked-list', 'nodes', 'pointers', 'sequential'],
    mode: 'interactive',
  },
  {
    id: 'doubly-linked-list',
    name: 'Doubly Linked List',
    category: 'linkedlist',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Nodes containing values and two pointers pointing to the next and previous nodes.',
    tags: ['linked-list', 'doubly-linked', 'pointers'],
    mode: 'interactive',
  },
  {
    id: 'circular-linked-list',
    name: 'Circular Linked List',
    category: 'linkedlist',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'A linked list where the last node points back to the first node, forming a loop.',
    tags: ['linked-list', 'circular', 'pointers'],
    mode: 'interactive',
  },
  {
    id: 'reverse-linked-list',
    name: 'Reverse Linked List',
    category: 'linkedlist',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Inverts node pointer directions so the head points to the tail and nodes link backwards.',
    tags: ['linked-list', 'pointers'],
    mode: 'concept',
  },
  {
    id: 'reverse-k-groups',
    name: 'Reverse in K-Groups',
    category: 'linkedlist',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Reverses segments of a linked list in chunks of size k recursively.',
    tags: ['linked-list', 'pointers', 'recursion'],
    mode: 'concept',
  },
  {
    id: 'detect-cycle-linked-list',
    name: 'Detect Cycle (Linked List)',
    category: 'linkedlist',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Finds if a loop exists in pointers using Floyd’s Tortoise and Hare pointers.',
    tags: ['linked-list', 'pointers', 'floyd-cycle'],
    mode: 'concept',
  },
  {
    id: 'find-middle-linked-list',
    name: 'Find Middle Node',
    category: 'linkedlist',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Locates middle node in a single pass using slow and fast runner pointers.',
    tags: ['linked-list', 'pointers', 'two-pointers'],
    mode: 'concept',
  },
  {
    id: 'merge-linked-lists',
    name: 'Merge Two Sorted Lists',
    category: 'linkedlist',
    timeComplexity: 'O(n + m)',
    spaceComplexity: 'O(1)',
    description: 'Combines two sorted lists into one sorted output list by splicing pointers.',
    tags: ['linked-list', 'pointers', 'merge'],
    mode: 'concept',
  },
  {
    id: 'palindrome-linked-list',
    name: 'Palindrome Linked List',
    category: 'linkedlist',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Checks if linked values are identical forward/backward by reversing half the list.',
    tags: ['linked-list', 'pointers', 'palindrome'],
    mode: 'concept',
  },
  {
    id: 'remove-nth-node',
    name: 'Remove Nth Node From End',
    category: 'linkedlist',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Deletes the N-th node from the tail using a pointer gap offset.',
    tags: ['linked-list', 'pointers', 'two-pointers'],
    mode: 'concept',
  },
  {
    id: 'intersection-point-linked-list',
    name: 'Intersection of Two Lists',
    category: 'linkedlist',
    timeComplexity: 'O(n + m)',
    spaceComplexity: 'O(1)',
    description: 'Finds the node where two lists merge using length differences or pointer resets.',
    tags: ['linked-list', 'pointers', 'intersection'],
    mode: 'concept',
  },
  {
    id: 'flatten-linked-list',
    name: 'Flatten Multi-level List',
    category: 'linkedlist',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Transforms a multi-level list with down and next links into a flat single list.',
    tags: ['linked-list', 'pointers', 'flatten'],
    mode: 'concept',
  },
  {
    id: 'lru-cache',
    name: 'LRU Cache Design',
    category: 'linkedlist',
    timeComplexity: 'O(1) operations',
    spaceComplexity: 'O(c)',
    description: 'Least Recently Used Cache implementation using a Doubly Linked List and Hash Map.',
    tags: ['data-structure-design', 'hashmap', 'linked-list', 'cache'],
    mode: 'concept',
  },

  // 8. Binary Trees
  {
    id: 'tree-inorder',
    name: 'Inorder Traversal',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    description: 'Traverses binary tree nodes in Left -> Root -> Right sequence.',
    tags: ['tree', 'traversal', 'dfs'],
    mode: 'concept',
  },
  {
    id: 'tree-preorder',
    name: 'Preorder Traversal',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    description: 'Traverses binary tree nodes in Root -> Left -> Right sequence.',
    tags: ['tree', 'traversal', 'dfs'],
    mode: 'concept',
  },
  {
    id: 'tree-postorder',
    name: 'Postorder Traversal',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    description: 'Traverses binary tree nodes in Left -> Right -> Root sequence.',
    tags: ['tree', 'traversal', 'dfs'],
    mode: 'concept',
  },
  {
    id: 'tree-levelorder',
    name: 'Level Order Traversal',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(w)',
    description: 'Traverses binary tree breadth-first (BFS) level by level using a queue.',
    tags: ['tree', 'traversal', 'bfs'],
    mode: 'concept',
  },
  {
    id: 'tree-zigzag',
    name: 'Zigzag Spiral Traversal',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Traverses tree level-by-level, reversing directions (left-to-right then right-to-left) dynamically.',
    tags: ['tree', 'traversal', 'stack'],
    mode: 'concept',
  },
  {
    id: 'tree-height',
    name: 'Height of Binary Tree',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    description: 'Computes maximum depth of a binary tree (max path length from root to leaf).',
    tags: ['tree', 'recursion', 'depth'],
    mode: 'concept',
  },
  {
    id: 'tree-max-path-sum',
    name: 'Maximum Path Sum',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    description: 'Finds the path in a tree that has the maximum sum of node values, which does not need to pass through root.',
    tags: ['tree', 'recursion', 'path-sum'],
    mode: 'concept',
  },
  {
    id: 'tree-boundary',
    name: 'Boundary Traversal',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    description: 'Prints left boundary nodes, leaves, and reverse right boundary nodes of a binary tree.',
    tags: ['tree', 'traversal', 'boundary'],
    mode: 'concept',
  },
  {
    id: 'tree-vertical',
    name: 'Vertical Order Traversal',
    category: 'binarytrees',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    description: 'Traverses a tree from left to right vertical lines, mapped by nodes’ horizontal coordinates.',
    tags: ['tree', 'traversal', 'coordinates'],
    mode: 'concept',
  },
  {
    id: 'lca-tree',
    name: 'Lowest Common Ancestor (LCA)',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Finds the lowest node in a tree that has both given nodes as descendants.',
    tags: ['tree', 'lca', 'ancestor'],
    mode: 'interactive',
  },
  {
    id: 'tree-diameter',
    name: 'Tree Diameter',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Finds the length of the longest path between any two nodes in a tree.',
    tags: ['tree', 'diameter', 'path'],
    mode: 'interactive',
  },
  {
    id: 'tree-isomorphism',
    name: 'Tree Isomorphism',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Determines if two trees are structurally identical regardless of node values/order.',
    tags: ['tree', 'isomorphism', 'structure'],
    mode: 'interactive',
  },
  {
    id: 'tree-serialize',
    name: 'Tree Serialize / Deserialize',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Convert a tree structure into string format and reconstruct the tree back.',
    tags: ['tree', 'serialization', 'dfs'],
    mode: 'interactive',
  },
  {
    id: 'syntax-tree',
    name: 'Abstract Syntax Tree (AST)',
    category: 'binarytrees',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Represents the hierarchical syntactic structure of source code written in a programming language.',
    tags: ['tree', 'compiler', 'parsing'],
    mode: 'interactive',
  },

  // 9. Binary Search Trees (BST)
  {
    id: 'bst',
    name: 'BST Insert & Traverse',
    category: 'bst',
    timeComplexity: 'O(log n) avg',
    spaceComplexity: 'O(n)',
    description: 'Insert values into a BST and visualize in/pre/post-order traversals.',
    tags: ['tree', 'binary-search', 'recursive'],
    mode: 'interactive',
  },
  {
    id: 'bst-delete',
    name: 'BST Delete Node',
    category: 'bst',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(h)',
    description: 'Deletes a node from a BST, handling leaf nodes, single child nodes, and nodes with two children (inorder successor swap).',
    tags: ['tree', 'bst', 'deletion'],
    mode: 'concept',
  },
  {
    id: 'bst-search',
    name: 'BST Search Key',
    category: 'bst',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(h)',
    description: 'Finds if a key exists in a BST by traversing left or right based on comparisons.',
    tags: ['tree', 'bst', 'search'],
    mode: 'concept',
  },
  {
    id: 'validate-bst',
    name: 'Validate BST',
    category: 'bst',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    description: 'Validates if a binary tree satisfies BST properties using lower and upper bounds.',
    tags: ['tree', 'bst', 'validation'],
    mode: 'concept',
  },
  {
    id: 'kth-smallest-bst',
    name: 'K-th Smallest in BST',
    category: 'bst',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    description: 'Finds the K-th smallest node element in a BST using inorder traversal tracking.',
    tags: ['tree', 'bst', 'inorder'],
    mode: 'concept',
  },
  {
    id: 'bst-floor-ceil',
    name: 'BST Floor & Ceil',
    category: 'bst',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(h)',
    description: 'Calculates floor (largest key <= val) and ceil (smallest key >= val) values in a BST.',
    tags: ['tree', 'bst', 'search'],
    mode: 'concept',
  },
  {
    id: 'bst-range-queries',
    name: 'BST Range Queries',
    category: 'bst',
    timeComplexity: 'O(log n + k)',
    spaceComplexity: 'O(h)',
    description: 'Queries and returns all keys in a BST that fall within a range [L, R].',
    tags: ['tree', 'bst', 'range-query'],
    mode: 'concept',
  },

  // 10. Balanced Trees
  {
    id: 'avl-tree',
    name: 'AVL Tree (Rotations)',
    category: 'balancedtrees',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(n)',
    description: 'Self-balancing BST using Left, Right, Left-Right, and Right-Left rotations.',
    tags: ['tree', 'self-balancing', 'rotations'],
    mode: 'interactive',
  },
  {
    id: 'red-black-tree',
    name: 'Red-Black Tree',
    category: 'balancedtrees',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(n)',
    description: 'A self-balancing binary search tree where each node has a color attribute (Red or Black).',
    tags: ['tree', 'self-balancing', 'red-black'],
    mode: 'interactive',
  },
  {
    id: 'splay-tree',
    name: 'Splay Tree',
    category: 'balancedtrees',
    timeComplexity: 'O(log n) amortized',
    spaceComplexity: 'O(n)',
    description: 'Self-balancing BST where recently accessed elements are rotated (splayed) to the root for fast lookup.',
    tags: ['tree', 'self-balancing', 'splay', 'amortized'],
    mode: 'concept',
  },
  {
    id: 'treap',
    name: 'Treap (Tree + Heap)',
    category: 'balancedtrees',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(n)',
    description: 'A randomized binary search tree where nodes are assigned random priorities and follow BST + Max-Heap structures.',
    tags: ['tree', 'randomized', 'bst', 'heap'],
    mode: 'concept',
  },
  {
    id: 'b-tree',
    name: 'B-Tree',
    category: 'balancedtrees',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(n)',
    description: 'A self-balancing search tree designed to work well on direct-access storage devices.',
    tags: ['tree', 'self-balancing', 'multi-way'],
    mode: 'interactive',
  },
  {
    id: 'b-plus-tree',
    name: 'B+ Tree',
    category: 'balancedtrees',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(n)',
    description: 'A multi-way balanced tree variant where data elements are stored in leaf nodes only, linked sequentially.',
    tags: ['tree', 'self-balancing', 'database-index'],
    mode: 'concept',
  },

  // 11. Heap Algorithms
  {
    id: 'heapify-ops',
    name: 'Heapify Operations',
    category: 'heap',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    description: 'Shifts a node down a binary tree recursively to restore the Max/Min Heap property.',
    tags: ['heap', 'heapify', 'tree-structure'],
    mode: 'concept',
  },
  {
    id: 'build-heap',
    name: 'Build Heap (Floyd)',
    category: 'heap',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Converts an unordered array into a Max-Heap in linear time by running heapify on non-leaf nodes.',
    tags: ['heap', 'build-heap', 'linear'],
    mode: 'concept',
  },
  {
    id: 'k-largest-elements',
    name: 'K Largest Elements',
    category: 'heap',
    timeComplexity: 'O(n log k)',
    spaceComplexity: 'O(k)',
    description: 'Finds the K largest elements in a stream/array using a min-heap structure.',
    tags: ['heap', 'top-k', 'stream'],
    mode: 'concept',
  },
  {
    id: 'median-stream',
    name: 'Median in a Stream',
    category: 'heap',
    timeComplexity: 'O(log n) insertion',
    spaceComplexity: 'O(n)',
    description: 'Finds the median of numbers added to a stream in real-time using Max-Heap and Min-Heap balances.',
    tags: ['heap', 'median', 'design'],
    mode: 'concept',
  },
  {
    id: 'merge-k-lists',
    name: 'Merge K Sorted Lists',
    category: 'heap',
    timeComplexity: 'O(N log k)',
    spaceComplexity: 'O(k)',
    description: 'Merges k sorted lists into a single sorted list using a min-heap tracking head nodes.',
    tags: ['heap', 'merge', 'multi-pointer'],
    mode: 'concept',
  },
  {
    id: 'priority-scheduling',
    name: 'Priority Scheduling',
    category: 'heap',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(n)',
    description: 'Visualizes how tasks with varying priority attributes are scheduled and resolved using heaps.',
    tags: ['heap', 'os-scheduler'],
    mode: 'concept',
  },

  // 12. Trie (Prefix Trees)
  {
    id: 'trie-insert',
    name: 'Trie Word Insert',
    category: 'trie',
    timeComplexity: 'O(L)',
    spaceComplexity: 'O(AL)',
    description: 'Inserts a word into a Trie by creating character node path segments.',
    tags: ['trie', 'insertion', 'strings'],
    mode: 'concept',
  },
  {
    id: 'trie-search',
    name: 'Trie Word Search',
    category: 'trie',
    timeComplexity: 'O(L)',
    spaceComplexity: 'O(1)',
    description: 'Searches if a complete word exists in the prefix tree.',
    tags: ['trie', 'search', 'strings'],
    mode: 'concept',
  },
  {
    id: 'trie-prefix-search',
    name: 'Trie Prefix Search',
    category: 'trie',
    timeComplexity: 'O(L)',
    spaceComplexity: 'O(1)',
    description: 'Finds if a prefix exists as a starting fragment of any word in the tree.',
    tags: ['trie', 'prefix', 'strings'],
    mode: 'concept',
  },
  {
    id: 'trie-autocomplete',
    name: 'Autocomplete Suggestions',
    category: 'trie',
    timeComplexity: 'O(L + N)',
    spaceComplexity: 'O(N)',
    description: 'Generates all suffix word suggestions matching a typed prefix query.',
    tags: ['trie', 'autocomplete', 'strings'],
    mode: 'concept',
  },
  {
    id: 'trie-word-dictionary',
    name: 'Word Dictionary (Regex)',
    category: 'trie',
    timeComplexity: 'O(2ᴸ) worst',
    spaceComplexity: 'O(1)',
    description: 'A trie supporting wildcards (like "." matching any character) using recursive backtracking search.',
    tags: ['trie', 'backtracking', 'regex'],
    mode: 'concept',
  },
  {
    id: 'trie-xor-max-pair',
    name: 'Maximum XOR Pair',
    category: 'trie',
    timeComplexity: 'O(32)',
    spaceComplexity: 'O(N)',
    description: 'Finds two numbers in an array that produce the maximum XOR result using a binary Trie.',
    tags: ['trie', 'binary', 'xor', 'bit-tricks'],
    mode: 'concept',
  },

  // 13. Hashing
  {
    id: 'hash-frequency-count',
    name: 'Frequency Count',
    category: 'hashing',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(u)',
    description: 'Counts the occurrences of unique elements in a dataset in a single pass using a hash map.',
    tags: ['hashmap', 'counting'],
    mode: 'concept',
  },
  {
    id: 'hash-two-sum',
    name: 'Two Sum Problem',
    category: 'hashing',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Finds indices of two elements that sum up to a target using hash map value check-ups.',
    tags: ['hashmap', 'two-pointers', 'arrays'],
    mode: 'concept',
  },
  {
    id: 'hash-group-anagrams',
    name: 'Group Anagrams',
    category: 'hashing',
    timeComplexity: 'O(n × L log L)',
    spaceComplexity: 'O(n)',
    description: 'Groups words that are anagrams of each other by sorting keys and mapping them in a hash table.',
    tags: ['hashmap', 'strings', 'anagrams'],
    mode: 'concept',
  },
  {
    id: 'hash-longest-consecutive',
    name: 'Longest Consecutive Sequence',
    category: 'hashing',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Finds the length of the longest consecutive elements sequence in an unsorted array using hash sets.',
    tags: ['hashset', 'sequences', 'arrays'],
    mode: 'concept',
  },
  {
    id: 'hash-rolling-hash',
    name: 'Rolling Hash (Rabin-Karp)',
    category: 'hashing',
    timeComplexity: 'O(1) update',
    spaceComplexity: 'O(1)',
    description: 'Calculates hashes of sliding substrings efficiently in constant time using modular arithmetic offsets.',
    tags: ['hash', 'rolling', 'strings'],
    mode: 'concept',
  },
  {
    id: 'hash-rabin-karp',
    name: 'Rabin-Karp String Matching',
    category: 'hashing',
    timeComplexity: 'O(n + m) avg',
    spaceComplexity: 'O(1)',
    description: 'Finds occurrences of a pattern in a text using rolling hashes to compare substring hashes.',
    tags: ['hashing', 'search', 'strings', 'rolling-hash'],
    mode: 'concept',
  },

  // 14. Graph Traversal
  {
    id: 'bfs',
    name: 'Breadth-First Search',
    category: 'graphtraversal',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Explores all neighbors at the current depth before going deeper.',
    tags: ['graph', 'queue', 'shortest-path'],
    mode: 'interactive',
  },
  {
    id: 'dfs',
    name: 'Depth-First Search',
    category: 'graphtraversal',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Explores as deep as possible before backtracking.',
    tags: ['graph', 'stack', 'recursive'],
    mode: 'interactive',
  },
  {
    id: 'graph-iterative-dfs',
    name: 'Iterative DFS',
    category: 'graphtraversal',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Traverses graphs depth-first using an explicit stack structure instead of recursion.',
    tags: ['graph', 'stack', 'iterative'],
    mode: 'concept',
  },
  {
    id: 'adjacency-matrix',
    name: 'Adjacency Matrix',
    category: 'graphtraversal',
    timeComplexity: 'O(V²)',
    spaceComplexity: 'O(V²)',
    description: 'A 2D array representation of a graph where indices indicate edge presence and weight.',
    tags: ['graph', 'matrix', 'representation'],
    mode: 'interactive',
  },
  {
    id: 'adjacency-list',
    name: 'Adjacency List',
    category: 'graphtraversal',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V + E)',
    description: 'An array of lists representing the vertices connected to each vertex in the graph.',
    tags: ['graph', 'list', 'representation'],
    mode: 'interactive',
  },

  // 15. Shortest Path
  {
    id: 'dijkstra',
    name: "Dijkstra's Algorithm",
    category: 'shortestpath',
    timeComplexity: 'O((V + E) log V)',
    spaceComplexity: 'O(V)',
    description: 'Finds shortest paths from a source to all other nodes in a positive-weighted graph.',
    tags: ['graph', 'weighted', 'shortest-path', 'greedy'],
    mode: 'interactive',
  },
  {
    id: 'a-star',
    name: 'A* Search Algorithm',
    category: 'shortestpath',
    timeComplexity: 'O(E log V)',
    spaceComplexity: 'O(V)',
    description: 'Heuristic-guided shortest path search algorithm.',
    tags: ['graph', 'heuristic', 'shortest-path'],
    mode: 'interactive',
  },
  {
    id: 'bellman-ford',
    name: 'Bellman-Ford Algorithm',
    category: 'shortestpath',
    timeComplexity: 'O(V × E)',
    spaceComplexity: 'O(V)',
    description: 'Computes single-source shortest paths on weighted graphs containing negative edges, detecting cycles.',
    tags: ['graph', 'shortest-path', 'negative-weights'],
    mode: 'concept',
  },
  {
    id: 'floyd-warshall',
    name: 'Floyd-Warshall Algorithm',
    category: 'shortestpath',
    timeComplexity: 'O(V³)',
    spaceComplexity: 'O(V²)',
    description: 'An all-pairs shortest path dynamic programming algorithm.',
    tags: ['graph', 'shortest-path', 'all-pairs', 'dp'],
    mode: 'concept',
  },
  {
    id: 'johnson-algorithm',
    name: "Johnson's Algorithm",
    category: 'shortestpath',
    timeComplexity: 'O(V² log V + VE)',
    spaceComplexity: 'O(V²)',
    description: 'All-pairs shortest path algorithm combining Bellman-Ford reweighting and Dijkstra.',
    tags: ['graph', 'shortest-path', 'reweighting'],
    mode: 'concept',
  },
  {
    id: 'spfa',
    name: 'SPFA (Shortest Path Faster)',
    category: 'shortestpath',
    timeComplexity: 'O(V × E) worst',
    spaceComplexity: 'O(V)',
    description: 'Queue-optimized version of Bellman-Ford which is much faster on random graphs.',
    tags: ['graph', 'shortest-path', 'queue-optimized'],
    mode: 'concept',
  },

  // 16. Minimum Spanning Tree (MST)
  {
    id: 'prim',
    name: "Prim's MST Algorithm",
    category: 'mst',
    timeComplexity: 'O(E log V)',
    spaceComplexity: 'O(V)',
    description: 'Greedy algorithm to find a Minimum Spanning Tree for a weighted graph.',
    tags: ['graph', 'mst', 'greedy'],
    mode: 'interactive',
  },
  {
    id: 'kruskal',
    name: "Kruskal's MST Algorithm",
    category: 'mst',
    timeComplexity: 'O(E log E)',
    spaceComplexity: 'O(V)',
    description: 'Builds a Minimum Spanning Tree by sorting edges and using Disjoint Set.',
    tags: ['graph', 'mst', 'union-find'],
    mode: 'interactive',
  },
  {
    id: 'boruvka',
    name: "Boruvka's MST Algorithm",
    category: 'mst',
    timeComplexity: 'O(E log V)',
    spaceComplexity: 'O(V)',
    description: 'Oldest MST algorithm, adding cheapest edges out of components in parallel phases.',
    tags: ['graph', 'mst', 'parallelizable'],
    mode: 'concept',
  },

  // 17. Topological Sorting
  {
    id: 'topological-sort',
    name: 'Topological Sort',
    category: 'topological',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Linear ordering of vertices in a DAG such that for every directed edge uv, u comes before v.',
    tags: ['graph', 'dag', 'ordering'],
    mode: 'interactive',
  },
  {
    id: 'topological-kahn',
    name: "Kahn's Algorithm (BFS)",
    category: 'topological',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'BFS-style topological sorting using node indegrees and tracking queue states.',
    tags: ['graph', 'dag', 'bfs', 'indegree'],
    mode: 'concept',
  },
  {
    id: 'topological-dfs',
    name: 'DFS Topological Sort',
    category: 'topological',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Topological sorting using recursion stack callbacks and pushing to array upon backtrack.',
    tags: ['graph', 'dag', 'dfs', 'stack'],
    mode: 'concept',
  },

  // 18. Connectivity
  {
    id: 'union-find',
    name: 'Union Find (Disjoint Set)',
    category: 'connectivity',
    timeComplexity: 'O(α(N))',
    spaceComplexity: 'O(N)',
    description: 'Keeps track of partitioned sets, optimized with union by rank and path compression.',
    tags: ['dsu', 'connectivity'],
    mode: 'concept',
  },
  {
    id: 'dsu-ops',
    name: 'DSU Rank and Compression',
    category: 'connectivity',
    timeComplexity: 'O(α(N))',
    spaceComplexity: 'O(N)',
    description: 'Highlights path compression and tree balance updates during union operations.',
    tags: ['dsu', 'utility'],
    mode: 'concept',
  },
  {
    id: 'connected-components',
    name: 'Connected Components',
    category: 'connectivity',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Finds subsets of connected nodes in undirected graphs using BFS/DFS traversals.',
    tags: ['graph', 'traversal'],
    mode: 'concept',
  },
  {
    id: 'strongly-connected-components',
    name: 'Strongly Connected Components',
    category: 'connectivity',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Locates components in directed graphs where every vertex is reachable from any other.',
    tags: ['graph', 'connectivity', 'scc'],
    mode: 'concept',
  },
  {
    id: 'kosaraju',
    name: "Kosaraju's SCC Algorithm",
    category: 'connectivity',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Finds SCCs using graph transpose and double DFS traversals.',
    tags: ['graph', 'connectivity', 'scc'],
    mode: 'concept',
  },
  {
    id: 'tarjan',
    name: "Tarjan's SCC Algorithm",
    category: 'connectivity',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Finds SCCs in a single DFS pass using node indices and low-link numbers.',
    tags: ['graph', 'connectivity', 'scc', 'low-link'],
    mode: 'concept',
  },

  // 19. Cycle Detection
  {
    id: 'cycle-undirected-dfs',
    name: 'Cycle Undirected DFS',
    category: 'cycledetection',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Detects loops in undirected graphs by tracking node parent pointers during DFS traversal.',
    tags: ['graph', 'cycle', 'dfs'],
    mode: 'concept',
  },
  {
    id: 'cycle-directed-dfs',
    name: 'Cycle Directed DFS',
    category: 'cycledetection',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Detects cycles in directed graphs by tracking nodes currently in the recursion stack (back-edges).',
    tags: ['graph', 'cycle', 'dfs', 'directed'],
    mode: 'concept',
  },
  {
    id: 'cycle-union-find',
    name: 'Cycle Detection (DSU)',
    category: 'cycledetection',
    timeComplexity: 'O(E log V)',
    spaceComplexity: 'O(V)',
    description: 'Finds cycles in undirected graphs by adding edges to a DSU and checking if endpoints share a parent.',
    tags: ['graph', 'cycle', 'dsu'],
    mode: 'concept',
  },
  {
    id: 'cycle-floyd',
    name: 'Floyd Cycle Detection',
    category: 'cycledetection',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Floyd’s loop detection using pointer speed differentials (tortoise and hare).',
    tags: ['pointers', 'cycle', 'two-pointers'],
    mode: 'concept',
  },

  // 20. Dynamic Programming (DP)
  {
    id: 'fibonacci-dp',
    name: 'Fibonacci (DP)',
    category: 'dp',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Computes Fibonacci sequence using memoization/tabulation.',
    tags: ['dp', 'memoization', 'tabulation'],
    mode: 'interactive',
  },
  {
    id: 'climbing-stairs',
    name: 'Climbing Stairs',
    category: 'dp',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Finds total ways to reach step n taking 1 or 2 steps (combinatorial 1D DP).',
    tags: ['dp', '1d-dp', 'combinatorics'],
    mode: 'concept',
  },
  {
    id: 'house-robber',
    name: 'House Robber',
    category: 'dp',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Maximizes rob amount without picking adjacent indexes (1D DP optimization).',
    tags: ['dp', '1d-dp', 'optimization'],
    mode: 'concept',
  },
  {
    id: 'decode-ways',
    name: 'Decode Ways',
    category: 'dp',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Counts the number of ways to decode a numeric string into alphabet sequences.',
    tags: ['dp', '1d-dp', 'strings'],
    mode: 'concept',
  },
  {
    id: 'lcs',
    name: 'Longest Common Subsequence',
    category: 'dp',
    timeComplexity: 'O(m × n)',
    spaceComplexity: 'O(m × n)',
    description: 'Finds the longest subsequence common to two strings.',
    tags: ['dp', 'strings', '2D-table'],
    mode: 'interactive',
  },
  {
    id: 'edit-distance',
    name: 'Edit Distance',
    category: 'dp',
    timeComplexity: 'O(m × n)',
    spaceComplexity: 'O(m × n)',
    description: 'Minimum operations to transform one string into another.',
    tags: ['dp', 'strings', '2D-table', 'levenshtein'],
    mode: 'interactive',
  },
  {
    id: 'knapsack-dp',
    name: '0/1 Knapsack (DP)',
    category: 'dp',
    timeComplexity: 'O(n × W)',
    spaceComplexity: 'O(n × W)',
    description: 'Maximize item values in a knapsack of limited weight capacity W.',
    tags: ['dp', 'optimization', '2D-table'],
    mode: 'interactive',
  },

  // 21. Greedy Algorithms
  {
    id: 'fractional-knapsack',
    name: 'Fractional Knapsack',
    category: 'greedy',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    description: 'Maximizes the value of items placed in a knapsack of capacity W by taking fractions of items if needed.',
    tags: ['greedy', 'knapsack', 'optimization'],
    mode: 'concept',
  },
  {
    id: 'activity-selection',
    name: 'Activity Selection (Interval Scheduling)',
    category: 'greedy',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    description: 'Selects the maximum number of mutually compatible activities that can be performed by a single person.',
    tags: ['greedy', 'scheduling', 'intervals'],
    mode: 'concept',
  },
  {
    id: 'huffman-coding-greedy',
    name: 'Huffman Coding (Greedy Design)',
    category: 'greedy',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    description: 'A greedy algorithm that assigns variable-length codes to input characters based on their frequencies of occurrence.',
    tags: ['greedy', 'compression', 'trees'],
    mode: 'concept',
  },
  {
    id: 'job-sequencing',
    name: 'Job Sequencing with Deadlines',
    category: 'greedy',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(n)',
    description: 'Schedules jobs to maximize profit, ensuring each scheduled job is completed before its deadline.',
    tags: ['greedy', 'scheduling', 'deadlines'],
    mode: 'concept',
  },
  {
    id: 'optimal-merge-patterns',
    name: 'Optimal Merge Pattern',
    category: 'greedy',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    description: 'Finds the optimal sequence to merge multiple sorted files such that the total comparison cost is minimized.',
    tags: ['greedy', 'merge', 'heap'],
    mode: 'concept',
  },

  // 22. Divide and Conquer
  {
    id: 'strassen-matrix',
    name: "Strassen's Matrix Multiplication",
    category: 'divideandconquer',
    timeComplexity: 'O(n^2.81)',
    spaceComplexity: 'O(n²)',
    description: 'An efficient algorithm to multiply two square matrices using block division and fewer recursive multiplications.',
    tags: ['divide-and-conquer', 'matrix', 'math'],
    mode: 'concept',
  },
  {
    id: 'median-of-medians',
    name: 'Median of Medians',
    category: 'divideandconquer',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'A deterministic selection algorithm that finds the k-th smallest element in an unsorted array in linear time.',
    tags: ['divide-and-conquer', 'selection', 'order-statistics'],
    mode: 'concept',
  },
  {
    id: 'closest-pair',
    name: 'Closest Pair of Points',
    category: 'divideandconquer',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    description: 'Finds the closest pair of points in a 2D coordinate plane using a recursive divide-and-conquer strategy.',
    tags: ['divide-and-conquer', 'geometry', 'points'],
    mode: 'concept',
  },

  // 23. Strings
  {
    id: 'kmp',
    name: 'KMP String Matching',
    category: 'strings',
    timeComplexity: 'O(n + m)',
    spaceComplexity: 'O(m)',
    description: 'Searches for a pattern within a text by precomputing a prefix lookup table to skip redundant matching alignments.',
    tags: ['strings', 'pattern-matching', 'lookup'],
    mode: 'concept',
  },
  {
    id: 'z-algorithm',
    name: 'Z-Algorithm',
    category: 'strings',
    timeComplexity: 'O(n + m)',
    spaceComplexity: 'O(n + m)',
    description: 'Finds occurrences of a pattern in a text using a Z-array where each element is the length of the longest common prefix starting at that index.',
    tags: ['strings', 'pattern-matching', 'prefix'],
    mode: 'concept',
  },
  {
    id: 'manachers',
    name: "Manacher's Algorithm",
    category: 'strings',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Finds the longest palindromic substring in a given string in linear time using symmetry properties and boundary mirrors.',
    tags: ['strings', 'palindrome', 'symmetry'],
    mode: 'concept',
  },
  {
    id: 'boyer-moore',
    name: 'Boyer-Moore String Search',
    category: 'strings',
    timeComplexity: 'O(n + m) avg',
    spaceComplexity: 'O(Σ)',
    description: 'A highly efficient string searching algorithm that aligns pattern and shifts it from right to left using bad character and good suffix rules.',
    tags: ['strings', 'pattern-matching', 'search'],
    mode: 'concept',
  },
  {
    id: 'aho-corasick',
    name: 'Aho-Corasick Automaton',
    category: 'strings',
    timeComplexity: 'O(n + m + k)',
    spaceComplexity: 'O(M × Σ)',
    description: 'A multi-pattern search algorithm that matches a dictionary of keywords simultaneously in a text using a trie-based state machine.',
    tags: ['strings', 'automaton', 'multi-pattern'],
    mode: 'concept',
  },
  {
    id: 'lcp-array',
    name: 'LCP Array Construction',
    category: 'strings',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Constructs the Longest Common Prefix array of adjacent sorted suffixes using Kasai’s linear time algorithm.',
    tags: ['strings', 'suffix', 'array'],
    mode: 'concept',
  },

  // 24. Bit Manipulation
  {
    id: 'single-number',
    name: 'Single Number Solver',
    category: 'bitmanipulation',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Identifies the unique number in an array where every other element appears twice, using XOR self-canceling properties.',
    tags: ['bits', 'xor', 'array'],
    mode: 'concept',
  },
  {
    id: 'hamming-weight',
    name: 'Hamming Weight (1-Bits Count)',
    category: 'bitmanipulation',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    description: 'Counts the number of set bits (1s) in a word using bitwise subtraction masks or popcount updates.',
    tags: ['bits', 'bitwise', 'popcount'],
    mode: 'concept',
  },
  {
    id: 'counting-bits',
    name: 'Counting Bits Array',
    category: 'bitmanipulation',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    description: 'Computes the number of set bits for all numbers in the range 0 to n using a 1D bitwise dynamic programming relation.',
    tags: ['bits', 'dp', 'bitwise'],
    mode: 'concept',
  },
  {
    id: 'reverse-bits',
    name: 'Reverse Bits (32-bit)',
    category: 'bitmanipulation',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    description: 'Reverses the binary digits of a 32-bit unsigned integer using hierarchical bitwise mask swaps.',
    tags: ['bits', 'bitwise', 'integer'],
    mode: 'concept',
  },
  {
    id: 'power-of-two',
    name: 'Power of Two Check',
    category: 'bitmanipulation',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    description: 'Determines if an integer is a power of two using the bitwise check n & (n - 1) == 0.',
    tags: ['bits', 'bitwise', 'math'],
    mode: 'concept',
  },
  {
    id: 'bitwise-and-range',
    name: 'Bitwise AND of Numbers Range',
    category: 'bitmanipulation',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    description: 'Calculates the bitwise AND of all numbers in a range [M, N] by identifying their common binary prefix.',
    tags: ['bits', 'bitwise', 'range'],
    mode: 'concept',
  },

  // 25. Number Theory
  {
    id: 'euclidean-gcd',
    name: 'Euclidean GCD Algorithm',
    category: 'numbertheory',
    timeComplexity: 'O(log(min(a,b)))',
    spaceComplexity: 'O(1)',
    description: 'Finds the Greatest Common Divisor of two numbers recursively using remainder modulo updates.',
    tags: ['math', 'number-theory', 'gcd'],
    mode: 'concept',
  },
  {
    id: 'extended-gcd',
    name: 'Extended Euclidean GCD',
    category: 'numbertheory',
    timeComplexity: 'O(log(min(a,b)))',
    spaceComplexity: 'O(log(min(a,b)))',
    description: 'Calculates the GCD and finding the coefficients x, y such that ax + by = gcd(a,b), used in modular inverses.',
    tags: ['math', 'number-theory', 'gcd'],
    mode: 'concept',
  },
  {
    id: 'sieve-eratosthenes',
    name: 'Sieve of Eratosthenes',
    category: 'numbertheory',
    timeComplexity: 'O(n log log n)',
    spaceComplexity: 'O(n)',
    description: 'Generates all prime numbers up to a given limit by iteratively marking multiples of found primes as composite.',
    tags: ['math', 'primes', 'number-theory'],
    mode: 'concept',
  },
  {
    id: 'prime-factorization',
    name: 'Prime Factorization',
    category: 'numbertheory',
    timeComplexity: 'O(√n)',
    spaceComplexity: 'O(log n)',
    description: 'Breaks down a number into its prime components, traversing up to its square root.',
    tags: ['math', 'primes', 'number-theory'],
    mode: 'concept',
  },
  {
    id: 'modular-exponentiation',
    name: 'Modular Exponentiation',
    category: 'numbertheory',
    timeComplexity: 'O(log power)',
    spaceComplexity: 'O(1)',
    description: 'Computes (base^power) % mod efficiently using binary base-squaring shifts.',
    tags: ['math', 'modular-arithmetic'],
    mode: 'concept',
  },
  {
    id: 'euler-totient',
    name: "Euler's Totient Phi Function",
    category: 'numbertheory',
    timeComplexity: 'O(√n)',
    spaceComplexity: 'O(1)',
    description: 'Calculates the count of positive integers up to n that are relatively prime (coprime) to n.',
    tags: ['math', 'primes', 'totient'],
    mode: 'concept',
  },

  // 26. Matrix
  {
    id: 'matrix-rotation',
    name: 'Matrix Rotation (90°)',
    category: 'matrix',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(1)',
    description: 'Rotates a square 2D array 90 degrees clockwise in-place by swapping transpose and horizontal reflect bounds.',
    tags: ['matrix', 'in-place', 'rotation'],
    mode: 'concept',
  },
  {
    id: 'spiral-traversal',
    name: 'Spiral Matrix Traversal',
    category: 'matrix',
    timeComplexity: 'O(m × n)',
    spaceComplexity: 'O(1)',
    description: 'Traverses and prints a 2D matrix in a clockwise spiral outer boundary pattern.',
    tags: ['matrix', 'traversal', 'array'],
    mode: 'concept',
  },
  {
    id: 'matrix-transpose',
    name: 'Matrix Transpose',
    category: 'matrix',
    timeComplexity: 'O(m × n)',
    spaceComplexity: 'O(m × n)',
    description: 'Transforms rows of a matrix into columns and vice-versa, reflecting indices across the main diagonal.',
    tags: ['matrix', 'transpose'],
    mode: 'concept',
  },
  {
    id: 'set-matrix-zeroes',
    name: 'Set Matrix Zeroes',
    category: 'matrix',
    timeComplexity: 'O(m × n)',
    spaceComplexity: 'O(1)',
    description: 'Finds cells containing 0 and sets their entire row and column to 0 using the matrix borders as state markers.',
    tags: ['matrix', 'in-place'],
    mode: 'concept',
  },
  {
    id: 'flood-fill',
    name: 'Flood Fill Algorithm',
    category: 'matrix',
    timeComplexity: 'O(m × n)',
    spaceComplexity: 'O(m × n)',
    description: 'Fills connected components of target color pixels with a new replacement color using DFS/BFS boundaries.',
    tags: ['matrix', 'recursion', 'dfs'],
    mode: 'concept',
  },

  // 27. Geometry
  {
    id: 'graham-scan',
    name: 'Graham Scan (Convex Hull)',
    category: 'geometry',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    description: 'Finds the convex hull of a set of 2D points by sorting polar angles and using orientation cross-product checks.',
    tags: ['geometry', 'convex-hull', 'polar-sort'],
    mode: 'concept',
  },
  {
    id: 'jarvis-march',
    name: 'Jarvis March (Gift Wrapping)',
    category: 'geometry',
    timeComplexity: 'O(n × h)',
    spaceComplexity: 'O(n)',
    description: 'Computes the convex hull perimeter points by repeatedly scanning coordinates to locate the leftmost orientations.',
    tags: ['geometry', 'convex-hull', 'gift-wrap'],
    mode: 'concept',
  },
  {
    id: 'line-intersection',
    name: 'Line Segment Intersection',
    category: 'geometry',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    description: 'Determines if two line segments cross in a plane using coordinate orientation collinearity checks.',
    tags: ['geometry', 'segments', 'orientation'],
    mode: 'concept',
  },
  {
    id: 'point-in-polygon',
    name: 'Point in Polygon (Ray Casting)',
    category: 'geometry',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Checks if a query coordinate point lies inside a custom polygon by casting a horizontal ray and counting edge crossings.',
    tags: ['geometry', 'ray-casting', 'polygon'],
    mode: 'concept',
  },
  {
    id: 'shoelace-formula',
    name: 'Shoelace Area Formula',
    category: 'geometry',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Calculates the area of a non-self-intersecting polygon using coordinate diagonal products.',
    tags: ['geometry', 'area', 'polygon'],
    mode: 'concept',
  },

  // 28. Network Flow
  {
    id: 'ford-fulkerson',
    name: 'Ford-Fulkerson Method',
    category: 'networkflow',
    timeComplexity: 'O(E × max_flow)',
    spaceComplexity: 'O(V)',
    description: 'Finds the maximum network flow by repeatedly searching for augmenting paths in residual capacity networks.',
    tags: ['graph', 'network-flow', 'dfs'],
    mode: 'concept',
  },
  {
    id: 'edmonds-karp',
    name: 'Edmonds-Karp Algorithm',
    category: 'networkflow',
    timeComplexity: 'O(V × E²)',
    spaceComplexity: 'O(V + E)',
    description: 'An implementation of Ford-Fulkerson using BFS to locate the shortest augmenting paths first.',
    tags: ['graph', 'network-flow', 'bfs'],
    mode: 'concept',
  },
  {
    id: 'dinics',
    name: "Dinic's Algorithm",
    category: 'networkflow',
    timeComplexity: 'O(V² × E)',
    spaceComplexity: 'O(V + E)',
    description: 'Accelerates network max flow search using level graphs created via BFS and blocking flows routed via DFS.',
    tags: ['graph', 'network-flow', 'level-graph'],
    mode: 'concept',
  },
  {
    id: 'push-relabel',
    name: 'Push-Relabel Algorithm',
    category: 'networkflow',
    timeComplexity: 'O(V³)',
    spaceComplexity: 'O(V + E)',
    description: 'Maintains preflow states on nodes, pushing excess capacities to adjacent nodes and adjusting node heights.',
    tags: ['graph', 'network-flow', 'relabel'],
    mode: 'concept',
  },
  {
    id: 'min-cut-max-flow',
    name: 'Min-Cut Max-Flow Theorem',
    category: 'networkflow',
    timeComplexity: 'O(max_flow)',
    spaceComplexity: 'O(V)',
    description: 'Determines the minimum capacity cut dividing source and sink, proving it matches the maximum achievable flow.',
    tags: ['graph', 'network-flow', 'cut'],
    mode: 'concept',
  },

  // 29. Segment Trees & Fenwick Trees
  {
    id: 'segment-tree-ops',
    name: 'Segment Tree Build & Query',
    category: 'segmenttrees',
    timeComplexity: 'O(n) / O(log n)',
    spaceComplexity: 'O(n)',
    description: 'Constructs a binary tree over an array range to answer range-min/sum queries and perform point updates in logarithmic time.',
    tags: ['tree', 'range-query', 'segment-tree'],
    mode: 'concept',
  },
  {
    id: 'segment-tree-lazy',
    name: 'Lazy Propagation Segment Tree',
    category: 'segmenttrees',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(n)',
    description: 'Performs range updates on a segment tree efficiently by delaying updates to children until node values are accessed.',
    tags: ['tree', 'range-update', 'lazy'],
    mode: 'concept',
  },
  {
    id: 'fenwick-tree',
    name: 'Fenwick Tree (Binary Indexed Tree)',
    category: 'segmenttrees',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(n)',
    description: 'A compact array representation that enables dynamic prefix sum updates and query ranges in O(log n) time.',
    tags: ['tree', 'prefix-sum', 'bit'],
    mode: 'interactive',
  },
  {
    id: 'rurq-fenwick',
    name: 'Range Update Range Query (DSU representation)',
    category: 'segmenttrees',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(n)',
    description: 'Utilizes two internal Fenwick trees to support range-add operations alongside range-sum queries in logarithmic time.',
    tags: ['tree', 'prefix-sum', 'range'],
    mode: 'concept',
  },

  // 30. Advanced Graph
  {
    id: 'eulerian-path',
    name: "Hierholzer's Eulerian Path",
    category: 'advancedgraph',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Finds a walk in a graph that visits every edge exactly once using recursive cycle merges.',
    tags: ['graph', 'eulerian', 'path'],
    mode: 'concept',
  },
  {
    id: 'tsp-dp',
    name: 'TSP (Held-Karp Dynamic Programming)',
    category: 'advancedgraph',
    timeComplexity: 'O(n² × 2ⁿ)',
    spaceComplexity: 'O(n × 2ⁿ)',
    description: 'Finds the optimal Traveling Salesman tour using subproblems tracked via state bitmasks.',
    tags: ['graph', 'tsp', 'dp', 'bitmask'],
    mode: 'concept',
  },
  {
    id: 'two-sat',
    name: '2-SAT Solver',
    category: 'advancedgraph',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V + E)',
    description: 'Solves 2-Satisfiability boolean problems in linear time by analyzing strongly connected components in implication graphs.',
    tags: ['graph', 'scc', 'sat'],
    mode: 'concept',
  },
  {
    id: 'bridges-articulation',
    name: 'Bridges & Articulation Points',
    category: 'advancedgraph',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description: 'Locates critical edges (bridges) and nodes (articulation points) whose removal increases graph component count using DFS traversal discovery logs.',
    tags: ['graph', 'dfs', 'connectivity', 'low-link'],
    mode: 'concept',
  },

  // 31. Randomized Algorithms
  {
    id: 'fisher-yates',
    name: 'Fisher-Yates Shuffle',
    category: 'randomized',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Shuffles array elements into unbiased random permutations by swapping elements with random index selections.',
    tags: ['randomized', 'shuffle', 'permutation'],
    mode: 'concept',
  },
  {
    id: 'reservoir-sampling',
    name: 'Reservoir Sampling',
    category: 'randomized',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(k)',
    description: 'Selects K items randomly from a stream of unknown/infinite length with uniform probability using replacement logic.',
    tags: ['randomized', 'stream', 'sampling'],
    mode: 'concept',
  },
  {
    id: 'monte-carlo',
    name: 'Monte Carlo Area Estimation',
    category: 'randomized',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    description: 'Approximates complex values (like Pi or integrals) by running large numbers of randomized coordinate sampling trials.',
    tags: ['randomized', 'simulation', 'math'],
    mode: 'concept',
  },
  {
    id: 'las-vegas-pivot',
    name: 'Las Vegas Pivot Choice',
    category: 'randomized',
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    description: 'Demonstrates algorithms that always return correct results but utilize randomized choices to optimize expected runtime boundaries.',
    tags: ['randomized', 'quicksort', 'pivot'],
    mode: 'concept',
  },

  // 32. Parallel / Distributed
  {
    id: 'mapreduce',
    name: 'MapReduce Concept Model',
    category: 'parallel',
    timeComplexity: 'O(1) concept',
    spaceComplexity: 'O(1)',
    description: 'Visualizes parallel chunk partitioning (Map stage) and aggregation sorting (Reduce stage) across nodes.',
    tags: ['distributed', 'parallel', 'mapreduce'],
    mode: 'concept',
  },
  {
    id: 'parallel-merge-sort',
    name: 'Parallel Merge Sort',
    category: 'parallel',
    timeComplexity: 'O(n / p + log p) avg',
    spaceComplexity: 'O(n)',
    description: 'Divides sorting subproblems across multiple worker processes, merging sorted subsections concurrently.',
    tags: ['parallel', 'sorting', 'divide-and-conquer'],
    mode: 'concept',
  },
  {
    id: 'producer-consumer',
    name: 'Producer-Consumer Pattern',
    category: 'parallel',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(c)',
    description: 'Concurrently schedules producer threads writing to a buffer and consumer threads reading, using locks/semaphores.',
    tags: ['parallel', 'concurrency', 'semaphore'],
    mode: 'concept',
  },
  {
    id: 'dining-philosophers',
    name: 'Dining Philosophers Solver',
    category: 'parallel',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    description: 'Classic synchronization puzzle demonstrating resource deadlock and dynamic fork reservation checks to avoid starvation.',
    tags: ['parallel', 'concurrency', 'deadlock'],
    mode: 'concept',
  },

  // 33. Machine Learning (CS Curriculum)
  {
    id: 'gradient-descent',
    name: 'Gradient Descent Optimization',
    category: 'ml',
    timeComplexity: 'O(epochs × n)',
    spaceComplexity: 'O(1)',
    description: 'Optimizes linear regression line coefficients (w, b) by taking step offsets opposite to computed loss function derivatives.',
    tags: ['ml', 'optimization', 'math'],
    mode: 'concept',
  },
  {
    id: 'k-means',
    name: 'K-Means Clustering',
    category: 'ml',
    timeComplexity: 'O(t × k × n)',
    spaceComplexity: 'O(n)',
    description: 'Partitions unlabeled data coordinates into K separate clusters, shifting centroids to coordinate averages iteratively.',
    tags: ['ml', 'clustering', 'unsupervised'],
    mode: 'concept',
  },
  {
    id: 'knn',
    name: 'K-Nearest Neighbors (KNN)',
    category: 'ml',
    timeComplexity: 'O(n × d) search',
    spaceComplexity: 'O(n)',
    description: 'Classifies coordinates based on label majorities among their K closest distance neighbors.',
    tags: ['ml', 'classification', 'lazy-learning'],
    mode: 'concept',
  },
  {
    id: 'decision-tree-induction',
    name: 'Decision Tree Induction',
    category: 'ml',
    timeComplexity: 'O(n × d)',
    spaceComplexity: 'O(nodes)',
    description: 'Constructs a classification flowchart tree by sorting attributes based on Information Gain split bounds.',
    tags: ['ml', 'classification', 'greedy'],
    mode: 'concept',
  },
  {
    id: 'perceptron',
    name: 'Single-Layer Perceptron',
    category: 'ml',
    timeComplexity: 'O(epochs × n)',
    spaceComplexity: 'O(1)',
    description: 'A basic neural network neuron that models binary classification boundaries by shifting weight vectors based on sign mistakes.',
    tags: ['ml', 'neural-network', 'classification'],
    mode: 'concept',
  },
];


