import React from 'react';
import { useAlgorithmStore } from '../store/algorithmStore';
import type { SortOrder } from '../algorithms/sorting';

// Pseudocode mapping for all supported algorithms
const PSEUDOCODE_REGISTRY: Record<string, string[]> = {
  // Searching
  'linear-search': [
    'procedure linearSearch(A : list, target : value)',
    '  for each index i from 0 to length(A)-1 do',
    '    if A[i] == target then',
    '      return i // Found target',
    '    end if',
    '  end for',
    '  return -1 // Target not found',
    'end procedure',
  ],
  'binary-search': [
    'procedure binarySearch(A : sorted list, target : value)',
    '  left := 0, right := length(A)-1',
    '  while left <= right do',
    '    mid := floor((left + right) / 2)',
    '    if A[mid] == target then return mid',
    '    else if A[mid] < target then left := mid + 1',
    '    else right := mid - 1',
    '  end while',
    '  return -1 // Target not found',
    'end procedure',
  ],
  'ternary-search': [
    'procedure ternarySearch(A : sorted list, target : value)',
    '  left := 0, right := length(A)-1',
    '  while left <= right do',
    '    mid1 := left + floor((right - left) / 3)',
    '    mid2 := right - floor((right - left) / 3)',
    '    if A[mid1] == target then return mid1',
    '    if A[mid2] == target then return mid2',
    '    if target < A[mid1] then right := mid1 - 1',
    '    else if target > A[mid2] then left := mid2 + 1',
    '    else left := mid1 + 1, right := mid2 - 1',
    '  end while',
    '  return -1 // Target not found',
    'end procedure',
  ],
  // Sorting
  'bubble-sort-asc': [
    'procedure bubbleSort(A : list of sortable items)',
    '  n := length(A)',
    '  for i := 0 to n-2 do',
    '    for j := 0 to n-i-2 do',
    '      if A[j] > A[j+1] then',
    '        swap(A[j], A[j+1])',
    '      end if',
    '    end for',
    '  end for',
    'end procedure',
  ],
  'bubble-sort-desc': [
    'procedure bubbleSort(A : list of sortable items)',
    '  n := length(A)',
    '  for i := 0 to n-2 do',
    '    for j := 0 to n-i-2 do',
    '      if A[j] < A[j+1] then',
    '        swap(A[j], A[j+1])',
    '      end if',
    '    end for',
    '  end for',
    'end procedure',
  ],
  'selection-sort-asc': [
    'procedure selectionSort(A : list of sortable items)',
    '  n := length(A)',
    '  for i := 0 to n-2 do',
    '    minIdx := i',
    '    for j := i+1 to n-1 do',
    '      if A[j] < A[minIdx] then minIdx := j',
    '    end for',
    '    if minIdx != i then swap(A[i], A[minIdx])',
    '  end for',
    'end procedure',
  ],
  'selection-sort-desc': [
    'procedure selectionSort(A : list of sortable items)',
    '  n := length(A)',
    '  for i := 0 to n-2 do',
    '    maxIdx := i',
    '    for j := i+1 to n-1 do',
    '      if A[j] > A[maxIdx] then maxIdx := j',
    '    end for',
    '    if maxIdx != i then swap(A[i], A[maxIdx])',
    '  end for',
    'end procedure',
  ],
  'insertion-sort-asc': [
    'procedure insertionSort(A : list of sortable items)',
    '  for i := 1 to length(A)-1 do',
    '    key := A[i]',
    '    j := i - 1',
    '    while j >= 0 and A[j] > key do',
    '      A[j+1] := A[j]',
    '      j := j - 1',
    '    end while',
    '    A[j+1] := key',
    '  end for',
    'end procedure',
  ],
  'insertion-sort-desc': [
    'procedure insertionSort(A : list of sortable items)',
    '  for i := 1 to length(A)-1 do',
    '    key := A[i]',
    '    j := i - 1',
    '    while j >= 0 and A[j] < key do',
    '      A[j+1] := A[j]',
    '      j := j - 1',
    '    end while',
    '    A[j+1] := key',
    '  end for',
    'end procedure',
  ],
  'merge-sort-asc': [
    'procedure mergeSort(A : list, left, right)',
    '  if left < right then',
    '    mid := floor((left + right) / 2)',
    '    mergeSort(A, left, mid)',
    '    mergeSort(A, mid + 1, right)',
    '    merge(A, left, mid, right)',
    '  end if',
    'end procedure',
    'procedure merge(A, left, mid, right)',
    '  // Merge: pick smaller element first',
  ],
  'merge-sort-desc': [
    'procedure mergeSort(A : list, left, right)',
    '  if left < right then',
    '    mid := floor((left + right) / 2)',
    '    mergeSort(A, left, mid)',
    '    mergeSort(A, mid + 1, right)',
    '    merge(A, left, mid, right)',
    '  end if',
    'end procedure',
    'procedure merge(A, left, mid, right)',
    '  // Merge: pick larger element first',
  ],
  'quick-sort-asc': [
    'procedure quickSort(A : list, low, high)',
    '  if low < high then',
    '    pivotIndex := partition(A, low, high)',
    '    quickSort(A, low, pivotIndex - 1)',
    '    quickSort(A, pivotIndex + 1, high)',
    '  end if',
    'end procedure',
    'procedure partition(A, low, high)',
    '  // Elements < pivot go left, >= pivot go right',
  ],
  'quick-sort-desc': [
    'procedure quickSort(A : list, low, high)',
    '  if low < high then',
    '    pivotIndex := partition(A, low, high)',
    '    quickSort(A, low, pivotIndex - 1)',
    '    quickSort(A, pivotIndex + 1, high)',
    '  end if',
    'end procedure',
    'procedure partition(A, low, high)',
    '  // Elements > pivot go left, <= pivot go right',
  ],
  'heap-sort-asc': [
    'procedure heapSort(A : list)',
    '  buildMaxHeap(A) // Rearrange array',
    '  for i := length(A)-1 down to 1 do',
    '    swap(A[0], A[i]) // Extract max root',
    '    heapify(A, i, 0) // Restore max-heap property',
    '  end for',
    'end procedure',
  ],
  'heap-sort-desc': [
    'procedure heapSort(A : list)',
    '  buildMinHeap(A) // Rearrange array',
    '  for i := length(A)-1 down to 1 do',
    '    swap(A[0], A[i]) // Extract min root',
    '    heapify(A, i, 0) // Restore min-heap property',
    '  end for',
    'end procedure',
  ],
  'pigeonhole-sort-asc': [
    'procedure pigeonholeSort(A : list of integers)',
    '  find min and max in A',
    '  range := max - min + 1',
    '  initialize holes array to empty lists',
    '  for each x in A do',
    '    holes[x - min].append(x) // Place in hole',
    '  end for',
    '  index := 0',
    '  for each hole in holes (ascending) do',
    '    while hole is not empty do',
    '      A[index] := hole.pop_front()',
    '      index := index + 1',
    '    end while',
    '  end for',
    'end procedure',
  ],
  'pigeonhole-sort-desc': [
    'procedure pigeonholeSort(A : list of integers)',
    '  find min and max in A',
    '  range := max - min + 1',
    '  initialize holes array to empty lists',
    '  for each x in A do',
    '    holes[x - min].append(x) // Place in hole',
    '  end for',
    '  index := 0',
    '  for each hole in holes (descending) do',
    '    while hole is not empty do',
    '      A[index] := hole.pop_front()',
    '      index := index + 1',
    '    end while',
    '  end for',
    'end procedure',
  ],
  bfs: [
    'procedure BFS(G, start_node)',
    '  let Q be a queue',
    '  Q.enqueue(start_node) and mark visited',
    '  while Q is not empty do',
    '    current := Q.dequeue()',
    '    for each neighbor N of current do',
    '      if N is not visited then',
    '        mark N visited and Q.enqueue(N)',
    '      end if',
    '    end for',
    '  end while',
    'end procedure',
  ],
  dfs: [
    'procedure DFS(G, start_node)',
    '  let S be a stack',
    '  S.push(start_node)',
    '  while S is not empty do',
    '    current := S.pop()',
    '    if current is not visited then',
    '      mark current as visited',
    '      for each neighbor N of current do',
    '        if N is not visited then S.push(N)',
    '      end for',
    '    end if',
    '  end while',
    'end procedure',
  ],
  dijkstra: [
    'procedure Dijkstra(G, start_node)',
    '  dist[start_node] := 0, all others := infinity',
    '  while unvisited is not empty do',
    '    u := node with min dist in unvisited',
    '    mark u as visited',
    '    for each neighbor v of u do',
    '      alt := dist[u] + weight(u, v)',
    '      if alt < dist[v] then',
    '        dist[v] := alt, prev[v] := u',
    '      end if',
    '    end for',
    '  end while',
    'end procedure',
  ],
  bst: [
    'procedure insertBST(root, val)',
    '  if root is null return Node(val)',
    '  if val < root.value then',
    '    root.left := insertBST(root.left, val)',
    '  else',
    '    root.right := insertBST(root.right, val)',
    '  end if',
    '  return root',
    'end procedure',
  ],
  'fibonacci-dp': [
    'procedure fibonacciDP(n)',
    '  let F be an array of size n+1',
    '  F[0] := 0, F[1] := 1 // Base cases',
    '  for i := 2 to n do',
    '    F[i] := F[i-1] + F[i-2]',
    '  end for',
    '  return F[n]',
    'end procedure',
  ],
  lcs: [
    'procedure LCS(s1, s2)',
    '  let dp be an (m+1) x (n+1) matrix',
    '  initialize base cases to 0',
    '  for i := 1 to m do',
    '    for j := 1 to n do',
    '      if s1[i-1] == s2[j-1] then',
    '        dp[i][j] := dp[i-1][j-1] + 1',
    '      else',
    '        dp[i][j] := max(dp[i-1][j], dp[i][j-1])',
    '      end if',
    '    end for',
    '  end for',
    '  return backtrackLCS(dp, s1, s2)',
  ],
  'edit-distance': [
    'procedure editDistance(s1, s2)',
    '  let dp be an (m+1) x (n+1) matrix',
    '  initialize base cases: dp[i][0] := i, dp[0][j] := j',
    '  for i := 1 to m do',
    '    for j := 1 to n do',
    '      if s1[i-1] == s2[j-1] then',
    '        dp[i][j] := dp[i-1][j-1]',
    '      else',
    '        dp[i][j] := min(Replace: dp[i-1][j-1], Insert: dp[i][j-1], Delete: dp[i-1][j]) + 1',
    '      end if',
    '    end for',
    '  end for',
    '  return dp[m][n]',
  ],
  factorial: [
    'procedure factorial(n)',
    '  if n <= 1 return 1 // Base case',
    '  subResult := factorial(n - 1)',
    '  result := n * subResult',
    '  return result',
    'end procedure',
  ],
  'tower-of-hanoi': [
    'procedure hanoi(n, source, target, aux)',
    '  if n == 1 then',
    '    move disk 1 from source to target',
    '    return',
    '  end if',
    '  hanoi(n - 1, source, aux, target)',
    '  move disk n from source to target',
    '  hanoi(n - 1, aux, target, source)',
    'end procedure',
  ],
  'a-star': [
    'procedure AStar(G, start, end)',
    '  gScore[start] := 0, fScore[start] := h(start)',
    '  while openSet is not empty do',
    '    current := node in openSet with min fScore',
    '    if current == end return reconstructPath(current)',
    '    for each neighbor of current do',
    '      tentative_g := gScore[current] + dist(current, neighbor)',
    '      if tentative_g < gScore[neighbor] then',
    '        prev[neighbor] := current, gScore[neighbor] := tentative_g',
    '        fScore[neighbor] := tentative_g + h(neighbor)',
    '      end if',
    '    end for',
    '  end while',
    'end procedure',
  ],
  prim: [
    'procedure Prim(G, start_node)',
    '  keys[start_node] := 0, all others := infinity',
    '  while unvisited is not empty do',
    '    u := extractMinKeyNode(unvisited)',
    '    add u to MST',
    '    for each neighbor v of u do',
    '      if weight(u, v) < keys[v] then',
    '        keys[v] := weight(u, v), parent[v] := u',
    '      end if',
    '    end for',
    '  end while',
    'end procedure',
  ],
  kruskal: [
    'procedure Kruskal(G)',
    '  sort G.edges by weight ascending',
    '  initialize Disjoint Sets (Union-Find) for nodes',
    '  for each edge (u, v) in sorted_edges do',
    '    if find(u) != find(v) then',
    '      add (u, v) to MST',
    '      union(u, v)',
    '    end if',
    '  end for',
    'end procedure',
  ],
  'avl-tree': [
    'procedure insertAVL(node, val)',
    '  node := insertBST(node, val)',
    '  updateHeight(node)',
    '  balance := getBalance(node)',
    '  if balance > 1 and val < node.left.val then return rotateRight(node)',
    '  if balance < -1 and val > node.right.val then return rotateLeft(node)',
    '  if balance > 1 and val > node.left.val then leftRotate(node.left), rightRotate(node)',
    '  if balance < -1 and val < node.right.val then rightRotate(node.right), leftRotate(node)',
    '  return node',
    'end procedure',
  ],
  'knapsack-dp': [
    'procedure Knapsack(weights, values, capacity W)',
    '  initialize dp[(n+1)][(W+1)] matrix to -1',
    '  set base cases dp[i][0] := 0, dp[0][j] := 0',
    '  for i := 1 to n do',
    '    for w := 1 to W do',
    '      if weight[i-1] <= w then',
    '        dp[i][w] := max(dp[i-1][w], dp[i-1][w-weight[i-1]] + value[i-1])',
    '      else',
    '        dp[i][w] := dp[i-1][w]',
    '      end if',
    '    end for',
    '  end for',
    '  return backtrackItemsSelected(dp)',
  ],
  'coin-change-dp': [
    'procedure CoinChange(coins, amount)',
    '  initialize dp[(n+1)][(amount+1)] matrix to -1',
    '  set base cases: dp[i][0] := 0, dp[0][j] := infinity',
    '  for i := 1 to n do',
    '    for w := 1 to amount do',
    '      if coins[i-1] <= w then',
    '        dp[i][w] := min(dp[i-1][w], dp[i][w-coins[i-1]] + 1)',
    '      else',
    '        dp[i][w] := dp[i-1][w]',
    '      end if',
    '    end for',
    '  end for',
    '  return backtrackCoinsSelected(dp)',
  ],
  'n-queens': [
    'procedure solveNQueens(board, col)',
    '  if col >= N then return true // Solution found',
    '  for row := 0 to N-1 do',
    '    if isSafe(board, row, col) then',
    '      placeQueen(board, row, col)',
    '      if solveNQueens(board, col + 1) return true',
    '      removeQueen(board, row, col) // Backtrack',
    '    end if',
    '  end for',
    '  return false',
    'end procedure',
  ],
  'stack-ops': [
    'class Stack:',
    '  procedure push(val):',
    '    if isFull() then return error',
    '    top := top + 1, array[top] := val',
    '  procedure pop():',
    '    if isEmpty() then return error',
    '    val := array[top], top := top - 1, return val',
    '  procedure peek():',
    '    if isEmpty() then return error',
    '    return array[top]',
  ],
  'queue-ops': [
    'class Queue:',
    '  procedure enqueue(val):',
    '    if isFull() then return error',
    '    rear := rear + 1, array[rear] := val',
    '  procedure dequeue():',
    '    if isEmpty() then return error',
    '    val := array[front], front := front + 1, return val',
  ],
  'singly-linked-list': [
    'procedure traverseList(head):',
    '  curr := head',
    '  while curr is not null do curr := curr.next',
    'procedure insertNode(prevNode, val):',
    '  newNode := Node(val)',
    '  newNode.next := prevNode.next, prevNode.next := newNode',
    'procedure deleteNode(prevNode, targetNode):',
    '  prevNode.next := targetNode.next',
    '  free(targetNode)',
  ],
  'postfix-eval': [
    'procedure evaluatePostfix(Expression):',
    '  for each token in Expression do',
    '    if token is operand then push(token)',
    '    else if token is operator then',
    '      val1 := pop(), val2 := pop()',
    '      result := applyOperator(token, val2, val1)',
    '      push(result)',
    '  return pop()',
  ],
  'prefix-eval': [
    'procedure evaluatePrefix(Expression):',
    '  for each token in Expression from right to left do',
    '    if token is operand then push(token)',
    '    else if token is operator then',
    '      val1 := pop(), val2 := pop()',
    '      result := applyOperator(token, val1, val2)',
    '      push(result)',
    '  return pop()',
  ],
  'double-ended-queue': [
    'class Deque:',
    '  procedure insertFront(val): // Insert at front index',
    '  procedure insertLast(val):  // Insert at rear index',
    '  procedure deleteFront():    // Remove from front index',
    '  procedure deleteLast():     // Remove from rear index',
  ],
  'circular-queue': [
    'class CircularQueue:',
    '  procedure enqueue(val):',
    '    if (rear + 1) % size == front then return Full',
    '    rear := (rear + 1) % size, array[rear] := val',
    '  procedure dequeue():',
    '    if front == rear then return Empty',
    '    front := (front + 1) % size, return array[front]',
  ],
  'priority-queue': [
    'class PriorityQueue (Max-Heap):',
    '  procedure insert(val):',
    '    heap.append(val), heapifyUp(length-1)',
    '  procedure extractMax():',
    '    maxVal := heap[0], heap[0] := heap.pop(), heapifyDown(0)',
    '    return maxVal',
  ],
  'doubly-linked-list': [
    'procedure insertAfter(node, val):',
    '  newNode := Node(val)',
    '  newNode.next := node.next, newNode.prev := node',
    '  if node.next != null then node.next.prev := newNode',
    '  node.next := newNode',
    'procedure deleteNode(node):',
    '  if node.prev != null then node.prev.next := node.next',
    '  if node.next != null then node.next.prev := node.prev',
    '  free(node)',
  ],
  'circular-linked-list': [
    'procedure traverseCircular(head):',
    '  curr := head',
    '  do',
    '    process(curr), curr := curr.next',
    '  while curr != head',
  ],
  'topological-sort': [
    'procedure topologicalSort(G):',
    '  let indegree be array of size V := 0',
    '  for each edge (u, v) in G do indegree[v]++',
    '  let Q be a queue of vertices with indegree == 0',
    '  while Q is not empty do',
    '    u := Q.dequeue(), append u to result',
    '    for each neighbor v of u do',
    '      indegree[v]--',
    '      if indegree[v] == 0 then Q.enqueue(v)',
  ],
  'adjacency-matrix': [
    '// Adjacency Matrix Representation',
    'class Graph:',
    '  matrix := 2D array of size V x V initialized to 0',
    '  procedure addEdge(u, v, weight):',
    '    matrix[u][v] := weight',
    '    if undirected then matrix[v][u] := weight',
  ],
  'adjacency-list': [
    '// Adjacency List Representation',
    'class Graph:',
    '  adjList := array of lists of size V',
    '  procedure addEdge(u, v, weight):',
    '    adjList[u].append((v, weight))',
    '    if undirected then adjList[v].append((u, weight))',
  ],
  'red-black-tree': [
    'procedure insertFixup(T, z):',
    '  while z.parent.color == RED do',
    '    if z.parent == z.parent.parent.left then',
    '      y := z.parent.parent.right // Uncle',
    '      if y.color == RED then recolor parent, uncle, grandparent',
    '      else left/right rotate and recolor',
  ],
  'b-tree': [
    'procedure insert(T, k):',
    '  r := T.root',
    '  if r.isFull then',
    '    s := Node(), T.root := s',
    '    splitChild(s, 0, r), insertNonFull(s, k)',
    '  else insertNonFull(r, k)',
  ],
  'trie-tree': [
    'procedure insertWord(root, word):',
    '  curr := root',
    '  for each char c in word do',
    '    if curr.children[c] is null then',
    '      curr.children[c] := new TrieNode()',
    '    curr := curr.children[c]',
    '  curr.isEndOfWord := true',
  ],
  'segment-tree': [
    'procedure queryRange(node, start, end, l, r):',
    '  if r < start or end < l then return null // Out of range',
    '  if l <= start and end <= r then return tree[node]',
    '  mid := floor((start + end) / 2)',
    '  leftVal := queryRange(2*node, start, mid, l, r)',
    '  rightVal := queryRange(2*node+1, mid+1, end, l, r)',
    '  return merge(leftVal, rightVal)',
  ],
  'fenwick-tree': [
    'procedure queryPrefix(idx):',
    '  sum := 0',
    '  while idx > 0 do',
    '    sum := sum + tree[idx]',
    '    idx := idx - (idx & -idx) // Remove lowest set bit',
    '  return sum',
  ],
  'lca-tree': [
    'procedure findLCA(root, p, q):',
    '  if root is null or root == p or root == q return root',
    '  left := findLCA(root.left, p, q)',
    '  right := findLCA(root.right, p, q)',
    '  if left is not null and right is not null return root',
    '  return left if left is not null else right',
  ],
  'tree-diameter': [
    'procedure treeDiameter(root):',
    '  // Run DFS from arbitrary node A to find farthest node B',
    '  farthestNode := DFS(root, A)',
    '  // Run DFS from B to find its farthest node C',
    '  diameterPath := DFS(root, farthestNode)',
    '  return length(diameterPath)',
  ],
  'tree-isomorphism': [
    'procedure isIsomorphic(root1, root2):',
    '  if root1 is null and root2 is null return true',
    '  if root1 is null or root2 is null return false',
    '  if root1.value != root2.value return false',
    '  return (isIsomorphic(root1.left, root2.left) and isIsomorphic(root1.right, root2.right)) or',
    '         (isIsomorphic(root1.left, root2.right) and isIsomorphic(root1.right, root2.left))',
  ],
  'tree-serialize': [
    'procedure serialize(root):',
    '  if root is null return "#"',
    '  return root.value + "," + serialize(root.left) + "," + serialize(root.right)',
  ],
  'huffman-coding': [
    'procedure buildHuffmanTree(frequencies):',
    '  let PQ be priority queue of single-node trees sorted by frequency',
    '  while PQ.size > 1 do',
    '    left := PQ.extractMin(), right := PQ.extractMin()',
    '    parent := Node(frequency := left.freq + right.freq, left, right)',
    '    PQ.enqueue(parent)',
    '  return PQ.extractMin()',
  ],
  'decision-tree': [
    'procedure queryDecisionTree(node, input):',
    '  if node is leaf return node.label',
    '  if input[node.feature] <= node.threshold then',
    '    return queryDecisionTree(node.left, input)',
    '  else return queryDecisionTree(node.right, input)',
  ],
  'syntax-tree': [
    'procedure evaluateAST(node):',
    '  if node is leaf return node.value',
    '  leftVal := evaluateAST(node.left)',
    '  rightVal := evaluateAST(node.right)',
    '  return applyOperator(node.operator, leftVal, rightVal)',
  ],
  'shell-sort-asc': [
    'procedure shellSort(A : list of sortable items)',
    '  for gap := floor(n/2) down to 1 do',
    '    for i := gap to n-1 do',
    '      while j >= gap and A[j-gap] > key do',
    '        A[j] := A[j-gap]',
    '        j := j - gap',
    '      end while',
    '    end for',
    '  end for',
    'end procedure',
  ],
  'shell-sort-desc': [
    'procedure shellSort(A : list of sortable items)',
    '  for gap := floor(n/2) down to 1 do',
    '    for i := gap to n-1 do',
    '      while j >= gap and A[j-gap] < key do',
    '        A[j] := A[j-gap]',
    '        j := j - gap',
    '      end while',
    '    end for',
    '  end for',
    'end procedure',
  ],
  'counting-sort-asc': [
    'procedure countingSort(A : list of integers)',
    '  find max element in A to define range',
    '  initialize count array with 0s',
    '  for each val in A: count[val]++',
    '  accumulate prefix sums: count[i] += count[i-1]',
    '  for each val in A in reverse order:',
    '    output[count[val] - 1] := val',
    '    count[val]--',
    '  end for',
    '  copy output back to A // Ascending order',
    'end procedure',
  ],
  'counting-sort-desc': [
    'procedure countingSort(A : list of integers)',
    '  find max element in A to define range',
    '  initialize count array with 0s',
    '  for each val in A: count[val]++',
    '  accumulate reverse prefix sums',
    '  for each val in A in reverse order:',
    '    output[revCount[val] - 1] := val',
    '    revCount[val]--',
    '  end for',
    '  copy output back to A // Descending order',
    'end procedure',
  ],
  'radix-sort-asc': [
    'procedure radixSort(A : list of integers)',
    '  find max element in A to count digits',
    '  for exponent exp := 1 to max by x10 do',
    '    countingSortByDigit(A, exp)',
    '    build count and output arrays',
    '    place elements based on exp-th digit',
    '    copy output back to A',
    '  end for',
    '  return A // Ascending order',
    'end procedure',
  ],
  'radix-sort-desc': [
    'procedure radixSort(A : list of integers)',
    '  find max element in A to count digits',
    '  for exponent exp := 1 to max by x10 do',
    '    countingSortByDigit(A, exp)',
    '    build count and output arrays',
    '    place elements based on exp-th digit',
    '    copy output back to A',
    '  end for',
    '  reverse(A) // Descending order',
    '  return A',
    'end procedure',
  ],
  'bucket-sort-asc': [
    'procedure bucketSort(A : list)',
    '  find min and max values in A',
    '  create bucketCount empty buckets',
    '  for each val in A: place val in bucketIdx',
    '  for each bucket (ascending) do',
    '    sort(bucket) ascending',
    '    gather elements back to A',
    '  end for',
    '  return A',
    'end procedure',
  ],
  'bucket-sort-desc': [
    'procedure bucketSort(A : list)',
    '  find min and max values in A',
    '  create bucketCount empty buckets',
    '  for each val in A: place val in bucketIdx',
    '  for each bucket (descending) do',
    '    sort(bucket) descending',
    '    gather elements back to A',
    '  end for',
    '  return A',
    'end procedure',
  ],
  'fibonacci-recursive': [
    'procedure fibonacci(n):',
    '  if n <= 1 then',
    '    return n // Base case',
    '  end if',
    '  left := fibonacci(n - 1)',
    '  right := fibonacci(n - 2)',
    '  return left + right',
    'end procedure',
  ],
  'sum-of-n-recursive': [
    'procedure sumOfN(n):',
    '  if n <= 0 then',
    '    return 0 // Base case',
    '  end if',
    '  subSum := sumOfN(n - 1)',
    '  return n + subSum',
    'end procedure',
  ],
  'power-function-recursive': [
    'procedure power(x, n):',
    '  if n == 0 then',
    '    return 1 // Base case',
    '  end if',
    '  halfPower := power(x, floor(n / 2))',
    '  return n is even ? halfPower² : x * halfPower²',
    'end procedure',
  ],
  'sudoku-solver': [
    'procedure solveSudoku(grid):',
    '  find next empty cell (row, col)',
    '  if all cells filled return true',
    '  for num := 1 to 9 do',
    '    if isValid(grid, row, col, num) then',
    '      grid[row][col] := num',
    '      if solveSudoku(grid) return true',
    '      grid[row][col] := 0 // Backtrack',
    '    end if',
    '  end for',
    '  return false',
    'end procedure',
  ],
  'rat-in-a-maze': [
    'procedure solveMaze(grid, r, c):',
    '  if reached destination return true',
    '  mark cell [r, c] as visited',
    '  for each direction (Down, Right, Up, Left) do',
    '    if next cell is safe then',
    '      if solveMaze(grid, nextR, nextC) return true',
    '    end if',
    '  end for',
    '  mark cell [r, c] as dead-end // Backtrack',
    '  return false',
    'end procedure',
  ],
};

function getFallbackPseudocode(algoName: string, category: string): string[] {
  const procName = algoName.toLowerCase().replace(/[^a-z0-9]/g, '');
  
  switch (category) {
    case 'searching':
      return [
        `procedure ${procName}(A : sorted list, target : value)`,
        `  initialize search boundaries`,
        `  while search bounds are valid do`,
        `    compute probe index / partition pointers`,
        `    if A[pointer] == target then`,
        `      return pointer // Target found`,
        `    else if A[pointer] < target then`,
        `      adjust search range (move right/up)`,
        `    else`,
        `      adjust search range (move left/down)`,
        `    end if`,
        `  end while`,
        `  return -1 // Target not found`,
        `end procedure`
      ];
    case 'sorting':
      return [
        `procedure ${procName}(A : list of sortable items)`,
        `  n := length(A)`,
        `  initialize division boundaries or pass counts`,
        `  for each pass through the array do`,
        `    select element or compare element pairs`,
        `    if elements out of order then`,
        `      swap or shift elements to correct position`,
        `    end if`,
        `  end for`,
        `  return sorted list A`,
        `end procedure`
      ];
    case 'recursion':
    case 'divideandconquer':
      return [
        `procedure ${procName}(args)`,
        `  if baseCaseCondition(args) then`,
        `    return baseCaseValue`,
        `  end if`,
        `  divide problem into smaller subproblems`,
        `  subResult := ${procName}(subProblemArgs)`,
        `  result := combine(subResult, currentArgs)`,
        `  return result`,
        `end procedure`
      ];
    case 'backtracking':
      return [
        `procedure ${procName}(state, candidateIndex)`,
        `  if goalReached(state) then`,
        `    recordSolution(state)`,
        `    return true`,
        `  end if`,
        `  for each candidate choice c do`,
        `    if isValid(c, state) then`,
        `      makeChoice(c, state)`,
        `      if ${procName}(state, candidateIndex + 1) return true`,
        `      removeChoice(c, state) // Backtrack`,
        `    end if`,
        `  end for`,
        `  return false`,
        `end procedure`
      ];
    case 'stack':
    case 'queue-deque':
    case 'linkedlist':
      return [
        `class ${algoName.replace(/\s+/g, '')}:`,
        `  procedure initialize():`,
        `    set front, rear, or top pointers`,
        `  procedure push_enqueue_insert(val):`,
        `    if structure is full return overflow`,
        `    allocate node or adjust pointers`,
        `    insert value at target position`,
        `  procedure pop_dequeue_delete():`,
        `    if structure is empty return underflow`,
        `    retrieve value and update pointers`,
        `    return value`,
        `  procedure traverse_display():`,
        `    visit each node sequentially`
      ];
    case 'bst':
    case 'balancedtrees':
    case 'binarytrees':
      return [
        `procedure ${procName}(node, val)`,
        `  if node is null return new Node(val)`,
        `  if val < node.value then`,
        `    node.left := ${procName}(node.left, val)`,
        `  else`,
        `    node.right := ${procName}(node.right, val)`,
        `  end if`,
        `  balance/restructure tree if required`,
        `  return node`,
        `end procedure`
      ];
    case 'dp':
      return [
        `procedure ${procName}(input)`,
        `  allocate table or memoization array`,
        `  initialize base cases in table`,
        `  for each state transition do`,
        `    table[state] := computeTransition(table, state)`,
        `  end for`,
        `  return table[finalState]`,
        `end procedure`
      ];
    case 'graphtraversal':
    case 'shortestpath':
    case 'mst':
    case 'topological':
    case 'connectivity':
    case 'cycledetection':
    case 'networkflow':
    case 'advancedgraph':
      return [
        `procedure ${procName}(Graph G, source)`,
        `  initialize status structures (dist, visited, parent)`,
        `  add source node to processing container (Q / S / Heap)`,
        `  while container is not empty do`,
        `    u := extractNextNode(container)`,
        `    for each neighbor v of u do`,
        `      if weight/relax condition matches then`,
        `        update neighbor state and enqueue/push v`,
        `      end if`,
        `      process edge (u, v)`,
        `    end for`,
        `  end while`,
        `  return result path / structure`,
        `end procedure`
      ];
    default:
      return [
        `procedure ${procName}(input)`,
        `  initialize variables`,
        `  for each step of execution do`,
        `    evaluate algorithm conditions`,
        `    perform state adjustments`,
        `    update visualization step output`,
        `  end for`,
        `  return final result`,
        `end procedure`
      ];
  }
}

export const CodePanel: React.FC = () => {
  const { selectedAlgo, steps, currentStepIndex, sortOrder } = useAlgorithmStore();

  if (!selectedAlgo) return null;

  // For sorting algorithms, try order-specific pseudocode first
  const getSortingKey = (id: string, order: SortOrder) => `${id}-${order}`;
  const isSorting = selectedAlgo.category === 'sorting';
  const lookupKey = isSorting ? getSortingKey(selectedAlgo.id, sortOrder) : selectedAlgo.id;
  const lines = PSEUDOCODE_REGISTRY[lookupKey] || PSEUDOCODE_REGISTRY[selectedAlgo.id] || getFallbackPseudocode(selectedAlgo.name, selectedAlgo.category);
  const currentStep = steps[currentStepIndex];
  const highlightedLine = currentStep ? currentStep.codeLine : -1;

  return (
    <div className="w-full flex flex-col bg-white/80 dark:bg-zinc-900/60 border border-zinc-200 dark:border-zinc-800/80 rounded-xl overflow-hidden backdrop-blur-sm shadow-md transition-colors duration-300">
      <div className="bg-zinc-50 dark:bg-zinc-900 px-4 py-3 border-b border-zinc-200 dark:border-zinc-800/60 flex items-center justify-between transition-colors">
        <h4 className="text-xs uppercase font-mono font-semibold text-zinc-600 dark:text-zinc-400 tracking-wider">
          Pseudocode Execution
        </h4>
        <span className="text-[10px] font-mono text-zinc-500 dark:text-zinc-600 bg-zinc-200/50 dark:bg-zinc-950 px-2 py-0.5 rounded transition-colors">
          Sync Active
        </span>
      </div>

      <div className="p-4 overflow-x-auto font-mono text-xs leading-relaxed max-h-[300px]">
        <pre className="space-y-0.5">
          {lines.map((line, idx) => {
            // Line numbering starts at 1
            const lineNum = idx + 1;
            const isHighlighted = lineNum === highlightedLine;

            // Simple indentation rendering check
            const indentSpaces = line.search(/\S/);
            const indentPadding = indentSpaces > 0 ? ' '.repeat(indentSpaces) : '';
            const lineText = line.trim();

            return (
              <div
                key={idx}
                className={`flex w-full items-center py-0.5 px-2 rounded transition-colors duration-200 ${
                  isHighlighted
                    ? 'bg-violet-100 dark:bg-violet-950/80 text-violet-700 dark:text-violet-300 font-semibold border-l-2 border-violet-500 shadow-sm'
                    : 'text-zinc-600 dark:text-zinc-400 hover:bg-zinc-200/40 dark:hover:bg-zinc-800/20'
                }`}
              >
                {/* Line number spacer */}
                <span className="text-zinc-400 dark:text-zinc-600 select-none mr-4 w-4 text-right">
                  {lineNum}
                </span>

                {/* Code body */}
                <span>
                  {indentPadding}
                  {lineText}
                </span>
              </div>
            );
          })}
        </pre>
      </div>
    </div>
  );
};
